/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:15 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.repository.impl; 
import com.gateweb.charge.repository.*; 
import com.gateweb.charge.model.*;    
import com.gateweb.charge.*;

import com.meshinnovation.db.dao.exception.DaoSystemException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import java.util.Collection;
import javax.persistence.Query;
//import org.springframework.orm.ObjectRetrievalFailureException;
import java.util.List;
import java.util.ArrayList;
import javax.persistence.*;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaQuery;
import org.springframework.stereotype.Repository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import com.google.common.collect.Lists;
import com.querydsl.core.BooleanBuilder;


/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of PrepayDetail
 */
//@Repository("prepayDetailRepositoryCustom")
public class PrepayDetailRepositoryImpl implements PrepayDetailRepositoryCustom {
	
	/**
	 * <p>
	 * <code>Log</code> instance for this application.
	 * </p>
	 */
	protected final Log log = LogFactory.getLog(getClass());
	
	/*	@PersistenceContext
	private EntityManager em;

	public void setEntityManager(EntityManager em) {
		this.em = em;
	}*/

	@Autowired
	PrepayDetailRepository prepayDetailRepository;
	
	public PrepayDetailRepositoryImpl(){
	}
	

	@SuppressWarnings("unchecked")
	public List<PrepayDetailEntity> searchWithVo(PrepayDetailEntity vo) {
		log.debug("PrepayDetailRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QPrepayDetailEntity prepayDetailEntity = QPrepayDetailEntity.prepayDetailEntity;

		if ( vo.getCompanyId() != null ) {
			builder.and(prepayDetailEntity.companyId.eq(vo.getCompanyId())); //java.lang.Integer
		}	
		if ( vo.getMoney() != null ) {
			builder.and(prepayDetailEntity.money.eq(vo.getMoney())); //java.lang.Integer
		}	
		if ( vo.getPrepayDeductMasterId() != null ) {
			builder.and(prepayDetailEntity.prepayDeductMasterId.eq(vo.getPrepayDeductMasterId())); //java.lang.Integer
		}	
		if ( vo.getPrepayDetailId() != null ) {
			builder.and(prepayDetailEntity.prepayDetailId.eq(vo.getPrepayDetailId())); //java.lang.Integer
		}	
		if ( vo.getCreatorId() != null ) {
			builder.and(prepayDetailEntity.creatorId.eq(vo.getCreatorId())); //java.lang.Integer
		}	
		if ( vo.getModifierId() != null ) {
			builder.and(prepayDetailEntity.modifierId.eq(vo.getModifierId())); //java.lang.Integer
		}	
		if ( vo.getCashDetailId() != null ) {
			builder.and(prepayDetailEntity.cashDetailId.eq(vo.getCashDetailId())); //java.lang.Integer
		}	
		if ( vo.getCalYm() != null && !"".equals(vo.getCalYm())) {
			builder.and(prepayDetailEntity.calYm.equalsIgnoreCase(vo.getCalYm())); //java.lang.String
		}
		if ( vo.getCreateDate() != null ) {
			builder.and(prepayDetailEntity.createDate.eq(vo.getCreateDate())); //java.sql.Timestamp
		}	
		if ( vo.getModifyDate() != null ) {
			builder.and(prepayDetailEntity.modifyDate.eq(vo.getModifyDate())); //java.sql.Timestamp
		}	
		log.debug("PrepayDetailRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(prepayDetailRepository.findAll(builder.getValue()));	
	}
	
	@SuppressWarnings("unchecked")
	public List<PrepayDetailEntity> searchWithVo(PrepayDetailEntity vo, Pageable pageable) {
		log.debug("PrepayDetailRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QPrepayDetailEntity prepayDetailEntity = QPrepayDetailEntity.prepayDetailEntity;

		if ( vo.getCompanyId() != null ) {
			builder.and(prepayDetailEntity.companyId.eq(vo.getCompanyId())); //java.lang.Integer
		}	
		if ( vo.getMoney() != null ) {
			builder.and(prepayDetailEntity.money.eq(vo.getMoney())); //java.lang.Integer
		}	
		if ( vo.getPrepayDeductMasterId() != null ) {
			builder.and(prepayDetailEntity.prepayDeductMasterId.eq(vo.getPrepayDeductMasterId())); //java.lang.Integer
		}	
		if ( vo.getPrepayDetailId() != null ) {
			builder.and(prepayDetailEntity.prepayDetailId.eq(vo.getPrepayDetailId())); //java.lang.Integer
		}	
		if ( vo.getCreatorId() != null ) {
			builder.and(prepayDetailEntity.creatorId.eq(vo.getCreatorId())); //java.lang.Integer
		}	
		if ( vo.getModifierId() != null ) {
			builder.and(prepayDetailEntity.modifierId.eq(vo.getModifierId())); //java.lang.Integer
		}	
		if ( vo.getCashDetailId() != null ) {
			builder.and(prepayDetailEntity.cashDetailId.eq(vo.getCashDetailId())); //java.lang.Integer
		}	
		if ( vo.getCalYm() != null && !"".equals(vo.getCalYm())) {
			builder.and(prepayDetailEntity.calYm.equalsIgnoreCase(vo.getCalYm())); //java.lang.String
		}
		if ( vo.getCreateDate() != null ) {
			builder.and(prepayDetailEntity.createDate.eq(vo.getCreateDate())); //java.sql.Timestamp
		}	
		if ( vo.getModifyDate() != null ) {
			builder.and(prepayDetailEntity.modifyDate.eq(vo.getModifyDate())); //java.sql.Timestamp
		}	
		log.debug("PrepayDetailRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(prepayDetailRepository.findAll(builder.getValue(), pageable));	
	}
	
	@SuppressWarnings("unchecked")
	public List<PrepayDetailEntity> searchWithVo(PrepayDetailEntity vo, int pageOffset, int pageSize) {
		Pageable pageable = new PageRequest(pageOffset, pageSize);
		return searchWithVo(vo, pageable);
	}
	
	@SuppressWarnings("unchecked")
	public List<PrepayDetailEntity> searchLikeVo(PrepayDetailEntity vo) {
		log.debug("PrepayDetailRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QPrepayDetailEntity prepayDetailEntity = QPrepayDetailEntity.prepayDetailEntity;

		if ( vo.getCompanyId() != null ) {
			builder.and(prepayDetailEntity.companyId.eq(vo.getCompanyId())); //java.lang.Integer
		}	
		if ( vo.getMoney() != null ) {
			builder.and(prepayDetailEntity.money.eq(vo.getMoney())); //java.lang.Integer
		}	
		if ( vo.getPrepayDeductMasterId() != null ) {
			builder.and(prepayDetailEntity.prepayDeductMasterId.eq(vo.getPrepayDeductMasterId())); //java.lang.Integer
		}	
		if ( vo.getPrepayDetailId() != null ) {
			builder.and(prepayDetailEntity.prepayDetailId.eq(vo.getPrepayDetailId())); //java.lang.Integer
		}	
		if ( vo.getCreatorId() != null ) {
			builder.and(prepayDetailEntity.creatorId.eq(vo.getCreatorId())); //java.lang.Integer
		}	
		if ( vo.getModifierId() != null ) {
			builder.and(prepayDetailEntity.modifierId.eq(vo.getModifierId())); //java.lang.Integer
		}	
		if ( vo.getCashDetailId() != null ) {
			builder.and(prepayDetailEntity.cashDetailId.eq(vo.getCashDetailId())); //java.lang.Integer
		}	
		if ( vo.getCalYm() != null && !"".equals(vo.getCalYm())) {
			builder.and(prepayDetailEntity.calYm.containsIgnoreCase(vo.getCalYm())); //java.lang.String
		}
		if ( vo.getCreateDate() != null ) {
			builder.and(prepayDetailEntity.createDate.eq(vo.getCreateDate())); //java.sql.Timestamp
		}	
		if ( vo.getModifyDate() != null ) {
			builder.and(prepayDetailEntity.modifyDate.eq(vo.getModifyDate())); //java.sql.Timestamp
		}	
		log.debug("PrepayDetailRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(prepayDetailRepository.findAll(builder.getValue()));
	}		
	
	

	@SuppressWarnings("unchecked")
	public List<PrepayDetailEntity> searchLikeVo(PrepayDetailEntity vo, Pageable pageable) {
		log.debug("PrepayDetailRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QPrepayDetailEntity prepayDetailEntity = QPrepayDetailEntity.prepayDetailEntity;

		if ( vo.getCompanyId() != null ) {
			builder.and(prepayDetailEntity.companyId.eq(vo.getCompanyId())); //java.lang.Integer
		}	
		if ( vo.getMoney() != null ) {
			builder.and(prepayDetailEntity.money.eq(vo.getMoney())); //java.lang.Integer
		}	
		if ( vo.getPrepayDeductMasterId() != null ) {
			builder.and(prepayDetailEntity.prepayDeductMasterId.eq(vo.getPrepayDeductMasterId())); //java.lang.Integer
		}	
		if ( vo.getPrepayDetailId() != null ) {
			builder.and(prepayDetailEntity.prepayDetailId.eq(vo.getPrepayDetailId())); //java.lang.Integer
		}	
		if ( vo.getCreatorId() != null ) {
			builder.and(prepayDetailEntity.creatorId.eq(vo.getCreatorId())); //java.lang.Integer
		}	
		if ( vo.getModifierId() != null ) {
			builder.and(prepayDetailEntity.modifierId.eq(vo.getModifierId())); //java.lang.Integer
		}	
		if ( vo.getCashDetailId() != null ) {
			builder.and(prepayDetailEntity.cashDetailId.eq(vo.getCashDetailId())); //java.lang.Integer
		}	
		if ( vo.getCalYm() != null && !"".equals(vo.getCalYm())) {
			builder.and(prepayDetailEntity.calYm.containsIgnoreCase(vo.getCalYm())); //java.lang.String
		}
		if ( vo.getCreateDate() != null ) {
			builder.and(prepayDetailEntity.createDate.eq(vo.getCreateDate())); //java.sql.Timestamp
		}	
		if ( vo.getModifyDate() != null ) {
			builder.and(prepayDetailEntity.modifyDate.eq(vo.getModifyDate())); //java.sql.Timestamp
		}	
		log.debug("PrepayDetailRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(prepayDetailRepository.findAll(builder.getValue(), pageable));
	}	
	
	@SuppressWarnings("unchecked")
	public List<PrepayDetailEntity> searchLikeVo(PrepayDetailEntity vo, int pageOffset, int pageSize) {
		Pageable pageable = new PageRequest(pageOffset, pageSize);
		return searchLikeVo(vo, pageable);
	}
	
}
