/*
 * $Header: $
 * This java source file is generated by pkliu on Thu Aug 03 11:22:57 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.einv.repository; 
    
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.gateweb.einv.model.Company;
import com.meshinnovation.db.dao.exception.DaoSystemException;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of Company
 */
 @Repository
public interface EinvCompanyRepository extends JpaRepository<Company, Long>
	, QuerydslPredicateExecutor<Company> ,EinvCompanyRepositoryCustom {
	
    /**
     * Delete a record in Database.
	 * @param $pkVar.columnName   PK 
	 * @throws DaoSystemException	if system is wrong.
     */
	void deleteByCompanyId(	
		java.lang.Long companyId 
	) throws DaoSystemException;

//	public Company findByCompanyId(Long companyId);
//	
//	public Page<Company> findByCompanyId(Long companyId, Pageable pageable);
//	
//	public boolean exists(Long companyId);
//	
//	public List<Company> findAll();
//	
//	public List<Company> findTop100ByCompanyId(Long companyId);
//	
//	public long count();

			
}

	