/*
 * $Header: $
 * This java source file is generated by pkliu on Thu Aug 03 11:22:57 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.einv.repository; 
    
import java.sql.SQLException;
import java.util.Collection;
import com.gateweb.einv.*;
import com.gateweb.einv.model.*;
import com.meshinnovation.db.dao.exception.DaoSystemException;
import java.io.Serializable;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of InvoiceDetails
 */
 @Repository("invoiceDetailsRepository")
public interface InvoiceDetailsRepository extends JpaRepository<InvoiceDetails, Long>
	, QueryDslPredicateExecutor<InvoiceDetails> ,InvoiceDetailsRepositoryCustom {
	
    /**
     * Delete a record in Database.
	 * @param $pkVar.columnName   PK 
	 * @throws DaoSystemException	if system is wrong.
     */
	void deleteByinvoiceDetailsId(	
		java.lang.Long invoiceDetailsId 
	) throws DaoSystemException;

	public InvoiceDetails findByInvoiceDetailsId(Long invoiceDetailsId);
	
	public Page<InvoiceDetails> findByInvoiceDetailsId(Long invoiceDetailsId, Pageable pageable);
	
	public boolean exists(Long invoiceDetailsId);
	
	public List<InvoiceDetails> findAll();
	
	public List<InvoiceDetails> findTop100ByInvoiceDetailsId(Long invoiceDetailsId);
	
	public long count();

			
}

	