/*
 * $Header: $
 * This java source file is generated by pkliu on Thu Aug 03 11:22:57 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.einv.repository; 
    
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.gateweb.einv.model.InvoiceMain;
import com.meshinnovation.db.dao.exception.DaoSystemException;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of InvoiceMain
 */
 @Repository("invoiceMainRepository")
public interface InvoiceMainRepository extends JpaRepository<InvoiceMain, Long>
	, QueryDslPredicateExecutor<InvoiceMain> ,InvoiceMainRepositoryCustom {
	
    /**
     * Delete a record in Database.
	 * @param $pkVar.columnName   PK 
	 * @throws DaoSystemException	if system is wrong.
     */
	void deleteByinvoiceId(	
		java.lang.Long invoiceId 
	) throws DaoSystemException;

	public InvoiceMain findByInvoiceId(Long invoiceId);
	
	public Page<InvoiceMain> findByInvoiceId(Long invoiceId, Pageable pageable);
	
	public boolean exists(Long invoiceId);
	
	public List<InvoiceMain> findAll();
	
	public List<InvoiceMain> findTop100ByInvoiceId(Long invoiceId);
	
	public long count();

			
}

	