/*
 * This file is generated by jOOQ.
 */
package com.gateweb.orm.charge.entity;


import com.gateweb.charge.enumeration.BillStatus;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "bill", schema = "public", uniqueConstraints = {
        @UniqueConstraint(name = "bill_pkey", columnNames = {"bill_id"})
})
public class Bill implements Serializable {

    private static final long serialVersionUID = -1681588709;

    private Long billId;
    private Long companyId;
    private BigDecimal taxRate;
    private BigDecimal taxAmount;
    private Boolean twTax;
    private BigDecimal taxExcludedAmount;
    private BigDecimal taxIncludedAmount;
    private BillStatus billStatus;
    private String billRemark;
    private String billYm;
    private String paymentRemark;
    private String bankCode;
    private LocalDateTime outToBankDate;
    private LocalDateTime paidDate;
    private Integer actualReceived;
    private String paymentMethod;
    private Boolean isMemo;
    private Long creatorId;
    private LocalDateTime createDate;

    public Bill() {
    }

    public Bill(Long billId, Long companyId, BigDecimal taxRate, BigDecimal taxAmount, Boolean twTax, BigDecimal taxExcludedAmount, BigDecimal taxIncludedAmount, BillStatus billStatus, String billRemark, String billYm, String paymentRemark, String bankCode, LocalDateTime outToBankDate, LocalDateTime paidDate, Integer actualReceived, String paymentMethod, Boolean isMemo, Long creatorId, LocalDateTime createDate) {
        this.billId = billId;
        this.companyId = companyId;
        this.taxRate = taxRate;
        this.taxAmount = taxAmount;
        this.twTax = twTax;
        this.taxExcludedAmount = taxExcludedAmount;
        this.taxIncludedAmount = taxIncludedAmount;
        this.billStatus = billStatus;
        this.billRemark = billRemark;
        this.billYm = billYm;
        this.paymentRemark = paymentRemark;
        this.bankCode = bankCode;
        this.outToBankDate = outToBankDate;
        this.paidDate = paidDate;
        this.actualReceived = actualReceived;
        this.paymentMethod = paymentMethod;
        this.isMemo = isMemo;
        this.creatorId = creatorId;
        this.createDate = createDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "bill_id", nullable = false, precision = 64)
    public Long getBillId() {
        return this.billId;
    }

    public void setBillId(Long billId) {
        this.billId = billId;
    }

    @Column(name = "company_id", precision = 64)
    public Long getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    @Column(name = "tax_rate", precision = 4, scale = 3)
    public BigDecimal getTaxRate() {
        return this.taxRate;
    }

    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    @Column(name = "tax_amount", precision = 13, scale = 4)
    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }

    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    @Column(name = "tw_tax")
    public Boolean getTwTax() {
        return this.twTax;
    }

    public void setTwTax(Boolean twTax) {
        this.twTax = twTax;
    }

    @Column(name = "tax_excluded_amount", precision = 23, scale = 4)
    public BigDecimal getTaxExcludedAmount() {
        return this.taxExcludedAmount;
    }

    public void setTaxExcludedAmount(BigDecimal taxExcludedAmount) {
        this.taxExcludedAmount = taxExcludedAmount;
    }

    @Column(name = "tax_included_amount", precision = 23, scale = 4)
    public BigDecimal getTaxIncludedAmount() {
        return this.taxIncludedAmount;
    }

    public void setTaxIncludedAmount(BigDecimal taxIncludedAmount) {
        this.taxIncludedAmount = taxIncludedAmount;
    }

    @Enumerated(EnumType.STRING)
    @Column(name = "bill_status")
    public BillStatus getBillStatus() {
        return billStatus;
    }

    public void setBillStatus(BillStatus billStatus) {
        this.billStatus = billStatus;
    }

    @Column(name = "bill_remark", length = 200)
    @Size(max = 200)
    public String getBillRemark() {
        return this.billRemark;
    }

    public void setBillRemark(String billRemark) {
        this.billRemark = billRemark;
    }

    @Column(name = "payment_remark", length = 200)
    @Size(max = 200)
    public String getPaymentRemark() {
        return this.paymentRemark;
    }

    public void setPaymentRemark(String paymentRemark) {
        this.paymentRemark = paymentRemark;
    }

    @Column(name = "bank_code", length = 20)
    @Size(max = 20)
    public String getBankCode() {
        return this.bankCode;
    }

    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    @Column(name = "out_to_bank_date")
    public LocalDateTime getOutToBankDate() {
        return this.outToBankDate;
    }

    public void setOutToBankDate(LocalDateTime outToBankDate) {
        this.outToBankDate = outToBankDate;
    }

    @Column(name = "paid_date")
    public LocalDateTime getPaidDate() {
        return this.paidDate;
    }

    public void setPaidDate(LocalDateTime paidDate) {
        this.paidDate = paidDate;
    }

    @Column(name = "actual_received", precision = 32)
    public Integer getActualReceived() {
        return this.actualReceived;
    }

    public void setActualReceived(Integer actualReceived) {
        this.actualReceived = actualReceived;
    }

    @Column(name = "payment_method", length = 30)
    @Size(max = 30)
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @Column(name = "is_memo")
    public Boolean getIsMemo() {
        return this.isMemo;
    }

    public void setIsMemo(Boolean isMemo) {
        this.isMemo = isMemo;
    }

    @Column(name = "creator_id", precision = 64)
    public Long getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    @Column(name = "create_date")
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    @Column(name = "bill_ym")
    public String getBillYm() {
        return billYm;
    }

    public void setBillYm(String billYm) {
        this.billYm = billYm;
    }

    @Override
    public String toString() {
        return "Bill{" +
                "billId=" + billId +
                ", companyId=" + companyId +
                ", taxRate=" + taxRate +
                ", taxAmount=" + taxAmount +
                ", twTax=" + twTax +
                ", taxExcludedAmount=" + taxExcludedAmount +
                ", taxIncludedAmount=" + taxIncludedAmount +
                ", billStatus=" + billStatus +
                ", billRemark='" + billRemark + '\'' +
                ", billYm='" + billYm + '\'' +
                ", paymentRemark='" + paymentRemark + '\'' +
                ", bankCode='" + bankCode + '\'' +
                ", outToBankDate=" + outToBankDate +
                ", paidDate=" + paidDate +
                ", actualReceived=" + actualReceived +
                ", paymentMethod='" + paymentMethod + '\'' +
                ", isMemo=" + isMemo +
                ", creatorId=" + creatorId +
                ", createDate=" + createDate +
                '}';
    }
}
