/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.orm.charge.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;


/**
 * @author pkliu
 */
@Entity
@Table(name = "bill_cycle")
public class BillCycleEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

    /**
     * cnt_over
     */
    @Column(name = "cnt_over")
    protected java.lang.Integer cntOver;

    /**
     * package_id
     */
    @Column(name = "package_id")
    protected java.lang.Integer packageId;

    /**
     * cash_in_over_id
     */
    @Column(name = "cash_in_over_id")
    protected java.lang.Integer cashInOverId;

    /**
     * pay_month
     */
    @Column(name = "pay_month")
    protected java.math.BigDecimal payMonth;

    /**
     * price_over
     */
    @Column(name = "price_over")
    protected java.math.BigDecimal priceOver;

    /**
     * single_price
     */
    @Column(name = "single_price")
    protected java.math.BigDecimal singlePrice;

    /**
     * price
     */
    @Column(name = "price")
    protected java.math.BigDecimal price;

    /**
     * bill_type
     */
    @Column(name = "bill_type")
    protected java.lang.Integer billType;

    /**
     * cnt_gift
     */
    @Column(name = "cnt_gift")
    protected java.lang.Integer cntGift;

    /**
     * cash_in_month_id
     */
    @Column(name = "cash_in_month_id")
    protected java.lang.Integer cashInMonthId;

    /**
     * create_date
     */
    @Column(name = "create_date")
    protected java.sql.Timestamp createDate;

    /**
     * bill_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "bill_id", unique = true, nullable = false)
    protected java.lang.Integer billId;

    /**
     * year_month
     */
    @Column(name = "year_month")
    protected java.lang.String yearMonth;

    /**
     * pay_over
     */
    @Column(name = "pay_over")
    protected java.math.BigDecimal payOver;

    /**
     * cash_out_month_id
     */
    @Column(name = "cash_out_month_id")
    protected java.lang.Integer cashOutMonthId;

    /**
     * company_id
     */
    @Column(name = "company_id")
    protected java.lang.Integer companyId;

    /**
     * cnt
     */
    @Column(name = "cnt")
    protected java.lang.Integer cnt;

    /**
     * cnt_limit
     */
    @Column(name = "cnt_limit")
    protected java.lang.Integer cntLimit;

    /**
     * modifier_id
     */
    @Column(name = "modifier_id")
    protected java.lang.Integer modifierId;

    /**
     * creator_id
     */
    @Column(name = "creator_id")
    protected java.lang.Integer creatorId;

    /**
     * is_price_free
     */
    @Column(name = "is_price_free")
    protected java.lang.String isPriceFree;

    /**
     * cash_out_over_id
     */
    @Column(name = "cash_out_over_id")
    protected java.lang.Integer cashOutOverId;

    /**
     * modify_date
     */
    @Column(name = "modify_date")
    protected java.sql.Timestamp modifyDate;

    /**
     * price_max
     */
    @Column(name = "price_max")
    protected java.math.BigDecimal priceMax;

    /**
     * status
     */
    @Column(name = "status")
    protected java.lang.String status;


    /**
     * 002
     *
     * @return java.lang.Integer cntOver
     */
    public java.lang.Integer getCntOver() {
        return this.cntOver;
    }

    /**
     * 0001
     *
     * @param data Set the cntOver
     */
    public void setCntOver(java.lang.Integer data) {
        this.cntOver = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer packageId
     */
    public java.lang.Integer getPackageId() {
        return this.packageId;
    }

    /**
     * 0001
     *
     * @param data Set the packageId
     */
    public void setPackageId(java.lang.Integer data) {
        this.packageId = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cashInOverId
     */
    public java.lang.Integer getCashInOverId() {
        return this.cashInOverId;
    }

    /**
     * 0001
     *
     * @param data Set the cashInOverId
     */
    public void setCashInOverId(java.lang.Integer data) {
        this.cashInOverId = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal payMonth
     */
    public java.math.BigDecimal getPayMonth() {
        return this.payMonth;
    }

    /**
     * 0001
     *
     * @param data Set the payMonth
     */
    public void setPayMonth(java.math.BigDecimal data) {
        this.payMonth = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal priceOver
     */
    public java.math.BigDecimal getPriceOver() {
        return this.priceOver;
    }

    /**
     * 0001
     *
     * @param data Set the priceOver
     */
    public void setPriceOver(java.math.BigDecimal data) {
        this.priceOver = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal singlePrice
     */
    public java.math.BigDecimal getSinglePrice() {
        return this.singlePrice;
    }

    /**
     * 0001
     *
     * @param data Set the singlePrice
     */
    public void setSinglePrice(java.math.BigDecimal data) {
        this.singlePrice = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal price
     */
    public java.math.BigDecimal getPrice() {
        return this.price;
    }

    /**
     * 0001
     *
     * @param data Set the price
     */
    public void setPrice(java.math.BigDecimal data) {
        this.price = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer billType
     */
    public java.lang.Integer getBillType() {
        return this.billType;
    }

    /**
     * 0001
     *
     * @param data Set the billType
     */
    public void setBillType(java.lang.Integer data) {
        this.billType = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cntGift
     */
    public java.lang.Integer getCntGift() {
        return this.cntGift;
    }

    /**
     * 0001
     *
     * @param data Set the cntGift
     */
    public void setCntGift(java.lang.Integer data) {
        this.cntGift = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cashInMonthId
     */
    public java.lang.Integer getCashInMonthId() {
        return this.cashInMonthId;
    }

    /**
     * 0001
     *
     * @param data Set the cashInMonthId
     */
    public void setCashInMonthId(java.lang.Integer data) {
        this.cashInMonthId = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp createDate
     */
    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }

    /**
     * 0001
     *
     * @param data Set the createDate
     */
    public void setCreateDate(java.sql.Timestamp data) {
        this.createDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer billId
     */
    public java.lang.Integer getBillId() {
        return this.billId;
    }

    /**
     * 0001
     *
     * @param data Set the billId
     */
    public void setBillId(java.lang.Integer data) {
        this.billId = data;    //zzz
    }

    /**
     * 002
     *
     * @return java.lang.String yearMonth
     */
    public java.lang.String getYearMonth() {
        return this.yearMonth;
    }

    /**
     * 0001
     *
     * @param data Set the yearMonth
     */
    public void setYearMonth(java.lang.String data) {
        this.yearMonth = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal payOver
     */
    public java.math.BigDecimal getPayOver() {
        return this.payOver;
    }

    /**
     * 0001
     *
     * @param data Set the payOver
     */
    public void setPayOver(java.math.BigDecimal data) {
        this.payOver = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cashOutMonthId
     */
    public java.lang.Integer getCashOutMonthId() {
        return this.cashOutMonthId;
    }

    /**
     * 0001
     *
     * @param data Set the cashOutMonthId
     */
    public void setCashOutMonthId(java.lang.Integer data) {
        this.cashOutMonthId = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer companyId
     */
    public java.lang.Integer getCompanyId() {
        return this.companyId;
    }

    /**
     * 0001
     *
     * @param data Set the companyId
     */
    public void setCompanyId(java.lang.Integer data) {
        this.companyId = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cnt
     */
    public java.lang.Integer getCnt() {
        return this.cnt;
    }

    /**
     * 0001
     *
     * @param data Set the cnt
     */
    public void setCnt(java.lang.Integer data) {
        this.cnt = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cntLimit
     */
    public java.lang.Integer getCntLimit() {
        return this.cntLimit;
    }

    /**
     * 0001
     *
     * @param data Set the cntLimit
     */
    public void setCntLimit(java.lang.Integer data) {
        this.cntLimit = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer modifierId
     */
    public java.lang.Integer getModifierId() {
        return this.modifierId;
    }

    /**
     * 0001
     *
     * @param data Set the modifierId
     */
    public void setModifierId(java.lang.Integer data) {
        this.modifierId = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer creatorId
     */
    public java.lang.Integer getCreatorId() {
        return this.creatorId;
    }

    /**
     * 0001
     *
     * @param data Set the creatorId
     */
    public void setCreatorId(java.lang.Integer data) {
        this.creatorId = data;
    }

    /**
     * 002
     *
     * @return java.lang.String isPriceFree
     */
    public java.lang.String getIsPriceFree() {
        return this.isPriceFree;
    }

    /**
     * 0001
     *
     * @param data Set the isPriceFree
     */
    public void setIsPriceFree(java.lang.String data) {
        this.isPriceFree = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cashOutOverId
     */
    public java.lang.Integer getCashOutOverId() {
        return this.cashOutOverId;
    }

    /**
     * 0001
     *
     * @param data Set the cashOutOverId
     */
    public void setCashOutOverId(java.lang.Integer data) {
        this.cashOutOverId = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp modifyDate
     */
    public java.sql.Timestamp getModifyDate() {
        return this.modifyDate;
    }

    /**
     * 0001
     *
     * @param data Set the modifyDate
     */
    public void setModifyDate(java.sql.Timestamp data) {
        this.modifyDate = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal priceMax
     */
    public java.math.BigDecimal getPriceMax() {
        return this.priceMax;
    }

    /**
     * 0001
     *
     * @param data Set the priceMax
     */
    public void setPriceMax(java.math.BigDecimal data) {
        this.priceMax = data;
    }

    /**
     * 002
     *
     * @return java.lang.String status
     */
    public java.lang.String getStatus() {
        return this.status;
    }

    /**
     * 0001
     *
     * @param data Set the status
     */
    public void setStatus(java.lang.String data) {
        this.status = data;
    }


    /**
     *
     */
    public BillCycleEntity() {
    }

    /**
     * full constructor
     *
     * @param cntOver
     * @param packageId
     * @param cashInOverId
     * @param payMonth
     * @param priceOver
     * @param singlePrice
     * @param price
     * @param billType
     * @param cntGift
     * @param cashInMonthId
     * @param createDate
     * @param billId
     * @param yearMonth
     * @param payOver
     * @param cashOutMonthId
     * @param companyId
     * @param cnt
     * @param cntLimit
     * @param modifierId
     * @param creatorId
     * @param isPriceFree
     * @param cashOutOverId
     * @param modifyDate
     * @param priceMax
     * @param status
     */
    public BillCycleEntity(
            java.lang.Integer cntOver
            , java.lang.Integer packageId
            , java.lang.Integer cashInOverId
            , java.math.BigDecimal payMonth
            , java.math.BigDecimal priceOver
            , java.math.BigDecimal singlePrice
            , java.math.BigDecimal price
            , java.lang.Integer billType
            , java.lang.Integer cntGift
            , java.lang.Integer cashInMonthId
            , java.sql.Timestamp createDate
            , java.lang.Integer billId
            , java.lang.String yearMonth
            , java.math.BigDecimal payOver
            , java.lang.Integer cashOutMonthId
            , java.lang.Integer companyId
            , java.lang.Integer cnt
            , java.lang.Integer cntLimit
            , java.lang.Integer modifierId
            , java.lang.Integer creatorId
            , java.lang.String isPriceFree
            , java.lang.Integer cashOutOverId
            , java.sql.Timestamp modifyDate
            , java.math.BigDecimal priceMax
            , java.lang.String status
    ) {
        this.setCntOver(cntOver);
        this.setPackageId(packageId);
        this.setCashInOverId(cashInOverId);
        this.setPayMonth(payMonth);
        this.setPriceOver(priceOver);
        this.setSinglePrice(singlePrice);
        this.setPrice(price);
        this.setBillType(billType);
        this.setCntGift(cntGift);
        this.setCashInMonthId(cashInMonthId);
        this.setCreateDate(createDate);
        this.setBillId(billId);
        this.setYearMonth(yearMonth);
        this.setPayOver(payOver);
        this.setCashOutMonthId(cashOutMonthId);
        this.setCompanyId(companyId);
        this.setCnt(cnt);
        this.setCntLimit(cntLimit);
        this.setModifierId(modifierId);
        this.setCreatorId(creatorId);
        this.setIsPriceFree(isPriceFree);
        this.setCashOutOverId(cashOutOverId);
        this.setModifyDate(modifyDate);
        this.setPriceMax(priceMax);
        this.setStatus(status);
    }

    @Override
    public int hashCode() {

        return Objects.hash(cntOver, packageId, cashInOverId, payMonth, priceOver, singlePrice, price, billType, cntGift, cashInMonthId, createDate, billId, yearMonth, payOver, cashOutMonthId, companyId, cnt, cntLimit, modifierId, creatorId, isPriceFree, cashOutOverId, modifyDate, priceMax, status);
    }

    @Override
    public String toString() {
        return "BillCycleEntity{" +
                "cntOver=" + cntOver +
                ", packageId=" + packageId +
                ", cashInOverId=" + cashInOverId +
                ", payMonth=" + payMonth +
                ", priceOver=" + priceOver +
                ", singlePrice=" + singlePrice +
                ", price=" + price +
                ", billType=" + billType +
                ", cntGift=" + cntGift +
                ", cashInMonthId=" + cashInMonthId +
                ", createDate=" + createDate +
                ", billId=" + billId +
                ", yearMonth='" + yearMonth + '\'' +
                ", payOver=" + payOver +
                ", cashOutMonthId=" + cashOutMonthId +
                ", companyId=" + companyId +
                ", cnt=" + cnt +
                ", cntLimit=" + cntLimit +
                ", modifierId=" + modifierId +
                ", creatorId=" + creatorId +
                ", isPriceFree='" + isPriceFree + '\'' +
                ", cashOutOverId=" + cashOutOverId +
                ", modifyDate=" + modifyDate +
                ", priceMax=" + priceMax +
                ", status='" + status + '\'' +
                '}';
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     *
     * @return true is equal, false is not equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof BillCycleEntity))
            return false;

        BillCycleEntity key = (BillCycleEntity) obj;
        if (this.billId != key.billId)
            return false;

        return true;
    }

}