/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.orm.charge.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;


/**
 * @author pkliu
 */
@Entity
@Table(name = "cash_master")
public class CashMasterEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

    /**
     * tax_amount
     */
    @Column(name = "tax_amount")
    protected java.math.BigDecimal taxAmount;

    /**
     * no_tax_inclusive_amount
     */
    @Column(name = "no_tax_inclusive_amount")
    protected java.math.BigDecimal noTaxInclusiveAmount;

    /**
     * company_id
     */
    @Column(name = "company_id")
    protected java.lang.Integer companyId;

    /**
     * in_date
     */
    @Column(name = "in_date")
    protected java.sql.Timestamp inDate;

    /**
     * out_date
     */
    @Column(name = "out_date")
    protected java.sql.Timestamp outDate;

    /**
     * is_first
     */
    @Column(name = "is_first")
    protected java.lang.String isFirst;

    /**
     * is_inout_money_unmatch
     */
    @Column(name = "is_inout_money_unmatch")
    protected java.lang.String isInoutMoneyUnmatch;

    /**
     * tax_rate
     */
    @Column(name = "tax_rate")
    protected java.lang.Float taxRate;

    /**
     * email_sent_date
     */
    @Column(name = "email_sent_date")
    protected java.sql.Timestamp emailSentDate;

    /**
     * in_amount
     */
    @Column(name = "in_amount")
    protected java.math.BigDecimal inAmount;

    /**
     * tax_inclusive_amount
     */
    @Column(name = "tax_inclusive_amount")
    protected java.math.BigDecimal taxInclusiveAmount;

    /**
     * cash_master_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "cash_master_id", unique = true, nullable = false)
    protected java.lang.Integer cashMasterId;

    /**
     * out_ym
     */
    @Column(name = "out_ym")
    protected java.lang.String outYm;

    /**
     * tax_type
     */
    @Column(name = "tax_type")
    protected java.lang.String taxType;

    /**
     * excel_out_date
     */
    @Column(name = "excel_out_date")
    protected java.sql.Timestamp excelOutDate;

    /**
     * creator_id
     */
    @Column(name = "creator_id")
    protected java.lang.Integer creatorId;

    /**
     * modifier_id
     */
    @Column(name = "modifier_id")
    protected java.lang.Integer modifierId;

    /**
     * create_date
     */
    @Column(name = "create_date")
    protected java.sql.Timestamp createDate;

    /**
     * in_note
     */
    @Column(name = "in_note")
    protected java.lang.String inNote;

    /**
     * modify_date
     */
    @Column(name = "modify_date")
    protected java.sql.Timestamp modifyDate;

    /**
     * bank_ym
     */
    @Column(name = "bank_ym")
    protected java.lang.String bankYm;

    /**
     * statusstatus
     */
    @Column(name = "status")
    protected java.lang.Integer status;


    /**
     * 002
     *
     * @return java.math.BigDecimal taxAmount
     */
    public java.math.BigDecimal getTaxAmount() {
        return this.taxAmount;
    }

    /**
     * 0001
     *
     * @param data Set the taxAmount
     */
    public void setTaxAmount(java.math.BigDecimal data) {
        this.taxAmount = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal noTaxInclusiveAmount
     */
    public java.math.BigDecimal getNoTaxInclusiveAmount() {
        return this.noTaxInclusiveAmount;
    }

    /**
     * 0001
     *
     * @param data Set the noTaxInclusiveAmount
     */
    public void setNoTaxInclusiveAmount(java.math.BigDecimal data) {
        this.noTaxInclusiveAmount = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer companyId
     */
    public java.lang.Integer getCompanyId() {
        return this.companyId;
    }

    /**
     * 0001
     *
     * @param data Set the companyId
     */
    public void setCompanyId(java.lang.Integer data) {
        this.companyId = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp inDate
     */
    public java.sql.Timestamp getInDate() {
        return this.inDate;
    }

    /**
     * 0001
     *
     * @param data Set the inDate
     */
    public void setInDate(java.sql.Timestamp data) {
        this.inDate = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp outDate
     */
    public java.sql.Timestamp getOutDate() {
        return this.outDate;
    }

    /**
     * 0001
     *
     * @param data Set the outDate
     */
    public void setOutDate(java.sql.Timestamp data) {
        this.outDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.String isFirst
     */
    public java.lang.String getIsFirst() {
        return this.isFirst;
    }

    /**
     * 0001
     *
     * @param data Set the isFirst
     */
    public void setIsFirst(java.lang.String data) {
        this.isFirst = data;
    }

    /**
     * 002
     *
     * @return java.lang.String isInoutMoneyUnmatch
     */
    public java.lang.String getIsInoutMoneyUnmatch() {
        return this.isInoutMoneyUnmatch;
    }

    /**
     * 0001
     *
     * @param data Set the isInoutMoneyUnmatch
     */
    public void setIsInoutMoneyUnmatch(java.lang.String data) {
        this.isInoutMoneyUnmatch = data;
    }

    /**
     * 002
     *
     * @return java.lang.Float taxRate
     */
    public java.lang.Float getTaxRate() {
        return this.taxRate;
    }

    /**
     * 0001
     *
     * @param data Set the taxRate
     */
    public void setTaxRate(java.lang.Float data) {
        this.taxRate = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp emailSentDate
     */
    public java.sql.Timestamp getEmailSentDate() {
        return this.emailSentDate;
    }

    /**
     * 0001
     *
     * @param data Set the emailSentDate
     */
    public void setEmailSentDate(java.sql.Timestamp data) {
        this.emailSentDate = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal inAmount
     */
    public java.math.BigDecimal getInAmount() {
        return this.inAmount;
    }

    /**
     * 0001
     *
     * @param data Set the inAmount
     */
    public void setInAmount(java.math.BigDecimal data) {
        this.inAmount = data;
    }

    /**
     * 002
     *
     * @return java.math.BigDecimal taxInclusiveAmount
     */
    public java.math.BigDecimal getTaxInclusiveAmount() {
        return this.taxInclusiveAmount;
    }

    /**
     * 0001
     *
     * @param data Set the taxInclusiveAmount
     */
    public void setTaxInclusiveAmount(java.math.BigDecimal data) {
        this.taxInclusiveAmount = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer cashMasterId
     */
    public java.lang.Integer getCashMasterId() {
        return this.cashMasterId;
    }

    /**
     * 0001
     *
     * @param data Set the cashMasterId
     */
    public void setCashMasterId(java.lang.Integer data) {
        this.cashMasterId = data;    //zzz
    }

    /**
     * 002
     *
     * @return java.lang.String outYm
     */
    public java.lang.String getOutYm() {
        return this.outYm;
    }

    /**
     * 0001
     *
     * @param data Set the outYm
     */
    public void setOutYm(java.lang.String data) {
        this.outYm = data;
    }

    /**
     * 002
     *
     * @return java.lang.String taxType
     */
    public java.lang.String getTaxType() {
        return this.taxType;
    }

    /**
     * 0001
     *
     * @param data Set the taxType
     */
    public void setTaxType(java.lang.String data) {
        this.taxType = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp excelOutDate
     */
    public java.sql.Timestamp getExcelOutDate() {
        return this.excelOutDate;
    }

    /**
     * 0001
     *
     * @param data Set the excelOutDate
     */
    public void setExcelOutDate(java.sql.Timestamp data) {
        this.excelOutDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer creatorId
     */
    public java.lang.Integer getCreatorId() {
        return this.creatorId;
    }

    /**
     * 0001
     *
     * @param data Set the creatorId
     */
    public void setCreatorId(java.lang.Integer data) {
        this.creatorId = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer modifierId
     */
    public java.lang.Integer getModifierId() {
        return this.modifierId;
    }

    /**
     * 0001
     *
     * @param data Set the modifierId
     */
    public void setModifierId(java.lang.Integer data) {
        this.modifierId = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp createDate
     */
    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }

    /**
     * 0001
     *
     * @param data Set the createDate
     */
    public void setCreateDate(java.sql.Timestamp data) {
        this.createDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.String inNote
     */
    public java.lang.String getInNote() {
        return this.inNote;
    }

    /**
     * 0001
     *
     * @param data Set the inNote
     */
    public void setInNote(java.lang.String data) {
        this.inNote = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp modifyDate
     */
    public java.sql.Timestamp getModifyDate() {
        return this.modifyDate;
    }

    /**
     * 0001
     *
     * @param data Set the modifyDate
     */
    public void setModifyDate(java.sql.Timestamp data) {
        this.modifyDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.String bankYm
     */
    public java.lang.String getBankYm() {
        return this.bankYm;
    }

    /**
     * 0001
     *
     * @param data Set the bankYm
     */
    public void setBankYm(java.lang.String data) {
        this.bankYm = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer status
     */
    public java.lang.Integer getStatus() {
        return this.status;
    }

    /**
     * 0001
     *
     * @param data Set the status
     */
    public void setStatus(java.lang.Integer data) {
        this.status = data;
    }


    /**
     *
     */
    public CashMasterEntity() {
    }

    /**
     * full constructor
     *
     * @param taxAmount
     * @param noTaxInclusiveAmount
     * @param companyId
     * @param inDate
     * @param outDate
     * @param isFirst
     * @param isInoutMoneyUnmatch
     * @param taxRate
     * @param emailSentDate
     * @param inAmount
     * @param taxInclusiveAmount
     * @param cashMasterId
     * @param outYm
     * @param taxType
     * @param excelOutDate
     * @param creatorId
     * @param modifierId
     * @param createDate
     * @param inNote
     * @param modifyDate
     * @param bankYm
     * @param status
     */
    public CashMasterEntity(
            java.math.BigDecimal taxAmount
            , java.math.BigDecimal noTaxInclusiveAmount
            , java.lang.Integer companyId
            , java.sql.Timestamp inDate
            , java.sql.Timestamp outDate
            , java.lang.String isFirst
            , java.lang.String isInoutMoneyUnmatch
            , java.lang.Float taxRate
            , java.sql.Timestamp emailSentDate
            , java.math.BigDecimal inAmount
            , java.math.BigDecimal taxInclusiveAmount
            , java.lang.Integer cashMasterId
            , java.lang.String outYm
            , java.lang.String taxType
            , java.sql.Timestamp excelOutDate
            , java.lang.Integer creatorId
            , java.lang.Integer modifierId
            , java.sql.Timestamp createDate
            , java.lang.String inNote
            , java.sql.Timestamp modifyDate
            , java.lang.String bankYm
            , java.lang.Integer status
    ) {
        this.setTaxAmount(taxAmount);
        this.setNoTaxInclusiveAmount(noTaxInclusiveAmount);
        this.setCompanyId(companyId);
        this.setInDate(inDate);
        this.setOutDate(outDate);
        this.setIsFirst(isFirst);
        this.setIsInoutMoneyUnmatch(isInoutMoneyUnmatch);
        this.setTaxRate(taxRate);
        this.setEmailSentDate(emailSentDate);
        this.setInAmount(inAmount);
        this.setTaxInclusiveAmount(taxInclusiveAmount);
        this.setCashMasterId(cashMasterId);
        this.setOutYm(outYm);
        this.setTaxType(taxType);
        this.setExcelOutDate(excelOutDate);
        this.setCreatorId(creatorId);
        this.setModifierId(modifierId);
        this.setCreateDate(createDate);
        this.setInNote(inNote);
        this.setModifyDate(modifyDate);
        this.setBankYm(bankYm);
        this.setStatus(status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(taxAmount, noTaxInclusiveAmount, companyId, inDate, outDate, isFirst, isInoutMoneyUnmatch, taxRate, emailSentDate, inAmount, taxInclusiveAmount, cashMasterId, outYm, taxType, excelOutDate, creatorId, modifierId, createDate, inNote, modifyDate, bankYm, status);
    }

    @Override
    public String toString() {
        return "CashMasterEntity{" +
                "taxAmount=" + taxAmount +
                ", noTaxInclusiveAmount=" + noTaxInclusiveAmount +
                ", companyId=" + companyId +
                ", inDate=" + inDate +
                ", outDate=" + outDate +
                ", isFirst='" + isFirst + '\'' +
                ", isInoutMoneyUnmatch='" + isInoutMoneyUnmatch + '\'' +
                ", taxRate=" + taxRate +
                ", emailSentDate=" + emailSentDate +
                ", inAmount=" + inAmount +
                ", taxInclusiveAmount=" + taxInclusiveAmount +
                ", cashMasterId=" + cashMasterId +
                ", outYm='" + outYm + '\'' +
                ", taxType='" + taxType + '\'' +
                ", excelOutDate=" + excelOutDate +
                ", creatorId=" + creatorId +
                ", modifierId=" + modifierId +
                ", createDate=" + createDate +
                ", inNote='" + inNote + '\'' +
                ", modifyDate=" + modifyDate +
                ", bankYm='" + bankYm + '\'' +
                ", status=" + status +
                '}';
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     *
     * @return true is equal, false is not equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CashMasterEntity))
            return false;

        CashMasterEntity key = (CashMasterEntity) obj;
        if (this.cashMasterId != key.cashMasterId)
            return false;

        return true;
    }

}