/*
 * This file is generated by jOOQ.
 */
package com.gateweb.orm.charge.entity;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contractor", schema = "public", indexes = {
    @Index(name = "contractor_id_pkey", unique = true, columnList = "contractor_id ASC")
})
public class Contractor implements Serializable {

    private static final long serialVersionUID = 1917457769;

    private Long      contractorId;
    private String    name;
    private String    businessNo;
    private String    phone;
    private String    email;
    private Integer   creatorId;
    private Timestamp createDate;
    private Integer   modifierId;
    private Timestamp modifyDate;

    public Contractor() {}

    public Contractor(Contractor value) {
        this.contractorId = value.contractorId;
        this.name = value.name;
        this.businessNo = value.businessNo;
        this.phone = value.phone;
        this.email = value.email;
        this.creatorId = value.creatorId;
        this.createDate = value.createDate;
        this.modifierId = value.modifierId;
        this.modifyDate = value.modifyDate;
    }

    public Contractor(
        Long      contractorId,
        String    name,
        String    businessNo,
        String    phone,
        String    email,
        Integer   creatorId,
        Timestamp createDate,
        Integer   modifierId,
        Timestamp modifyDate
    ) {
        this.contractorId = contractorId;
        this.name = name;
        this.businessNo = businessNo;
        this.phone = phone;
        this.email = email;
        this.creatorId = creatorId;
        this.createDate = createDate;
        this.modifierId = modifierId;
        this.modifyDate = modifyDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "contractor_id", unique = true, nullable = false, precision = 64)
    public Long getContractorId() {
        return this.contractorId;
    }

    public void setContractorId(Long contractorId) {
        this.contractorId = contractorId;
    }

    @Column(name = "name", length = 25)
    @Size(max = 25)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "business_no", nullable = false, length = 10)
    @NotNull
    @Size(max = 10)
    public String getBusinessNo() {
        return this.businessNo;
    }

    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo;
    }

    @Column(name = "phone", length = 25)
    @Size(max = 25)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "email", length = 50)
    @Size(max = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "creator_id", nullable = false, precision = 32)
    @NotNull
    public Integer getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    @Column(name = "create_date", nullable = false)
    @NotNull
    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Column(name = "modifier_id", precision = 32)
    public Integer getModifierId() {
        return this.modifierId;
    }

    public void setModifierId(Integer modifierId) {
        this.modifierId = modifierId;
    }

    @Column(name = "modify_date")
    public Timestamp getModifyDate() {
        return this.modifyDate;
    }

    public void setModifyDate(Timestamp modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contractor (");

        sb.append(contractorId);
        sb.append(", ").append(name);
        sb.append(", ").append(businessNo);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(modifierId);
        sb.append(", ").append(modifyDate);

        sb.append(")");
        return sb.toString();
    }
}
