/*
 * This file is generated by jOOQ.
 */
package com.gateweb.orm.charge.entity;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "contract_addition", schema = "public", indexes = {
    @Index(name = "contract_addition_pkey", unique = true, columnList = "addition_id ASC")
})
public class ContractAddition implements Serializable {

    private static final long serialVersionUID = -667214137;

    private Long      additionId;
    private Long      contractId;
    private String    source;
    private Long      sourceId;
    private Integer   creatorId;
    private Timestamp createDate;
    private Integer   modifierId;
    private Timestamp modifyDate;

    public ContractAddition() {}

    public ContractAddition(ContractAddition value) {
        this.additionId = value.additionId;
        this.contractId = value.contractId;
        this.source = value.source;
        this.sourceId = value.sourceId;
        this.creatorId = value.creatorId;
        this.createDate = value.createDate;
        this.modifierId = value.modifierId;
        this.modifyDate = value.modifyDate;
    }

    public ContractAddition(
        Long      additionId,
        Long      contractId,
        String    source,
        Long      sourceId,
        Integer   creatorId,
        Timestamp createDate,
        Integer   modifierId,
        Timestamp modifyDate
    ) {
        this.additionId = additionId;
        this.contractId = contractId;
        this.source = source;
        this.sourceId = sourceId;
        this.creatorId = creatorId;
        this.createDate = createDate;
        this.modifierId = modifierId;
        this.modifyDate = modifyDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "addition_id", unique = true, nullable = false, precision = 64)
    public Long getAdditionId() {
        return this.additionId;
    }

    public void setAdditionId(Long additionId) {
        this.additionId = additionId;
    }

    @Column(name = "contract_id", precision = 64)
    public Long getContractId() {
        return this.contractId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    @Column(name = "source", length = 25)
    @Size(max = 25)
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Column(name = "source_id", precision = 64)
    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    @Column(name = "creator_id", nullable = false, precision = 32)
    @NotNull
    public Integer getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    @Column(name = "create_date", nullable = false)
    @NotNull
    public Timestamp getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    @Column(name = "modifier_id", precision = 32)
    public Integer getModifierId() {
        return this.modifierId;
    }

    public void setModifierId(Integer modifierId) {
        this.modifierId = modifierId;
    }

    @Column(name = "modify_date")
    public Timestamp getModifyDate() {
        return this.modifyDate;
    }

    public void setModifyDate(Timestamp modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ContractAddition (");

        sb.append(additionId);
        sb.append(", ").append(contractId);
        sb.append(", ").append(source);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(modifierId);
        sb.append(", ").append(modifyDate);

        sb.append(")");
        return sb.toString();
    }
}
