/*
 * This file is generated by jOOQ.
 */
package com.gateweb.orm.charge.entity;


import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "invoice_remaining", schema = "public", uniqueConstraints = {
        @UniqueConstraint(name = "invoice_remaining_pkey", columnNames = {"invoice_remaining_id"})
})
public class InvoiceRemaining implements Serializable {

    private static final long serialVersionUID = 1457928482;

    private Long invoiceRemainingId;
    private Long companyId;
    private Long contractId;
    private Integer usage;
    private Integer remaining;
    private LocalDateTime uploadDate;
    private LocalDateTime createDate;
    private LocalDateTime modifyDate;
    private String invoiceDate;

    public InvoiceRemaining() {
    }

    public InvoiceRemaining(Long invoiceRemainingId, Long companyId, Long contractId, Integer usage, Integer remaining, LocalDateTime uploadDate, LocalDateTime createDate, LocalDateTime modifyDate, String invoiceDate) {
        this.invoiceRemainingId = invoiceRemainingId;
        this.companyId = companyId;
        this.contractId = contractId;
        this.usage = usage;
        this.remaining = remaining;
        this.uploadDate = uploadDate;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.invoiceDate = invoiceDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "invoice_remaining_id", nullable = false, precision = 64)
    public Long getInvoiceRemainingId() {
        return this.invoiceRemainingId;
    }

    public void setInvoiceRemainingId(Long invoiceRemainingId) {
        this.invoiceRemainingId = invoiceRemainingId;
    }

    @Column(name = "company_id", precision = 64)
    public Long getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    @Column(name = "contract_id", precision = 64)
    public Long getContractId() {
        return this.contractId;
    }

    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    @Column(name = "usage", precision = 32)
    public Integer getUsage() {
        return this.usage;
    }

    public void setUsage(Integer usage) {
        this.usage = usage;
    }

    @Column(name = "remaining", precision = 32)
    public Integer getRemaining() {
        return this.remaining;
    }

    public void setRemaining(Integer remaining) {
        this.remaining = remaining;
    }

    @Column(name = "upload_date")
    public LocalDateTime getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(LocalDateTime uploadDate) {
        this.uploadDate = uploadDate;
    }

    @Column(name = "create_date")
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    @Column(name = "modify_date")
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Column(name = "invoice_date", length = 8)
    @Size(max = 8)
    public String getInvoiceDate() {
        return this.invoiceDate;
    }

    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    @Override
    public String toString() {
        return "InvoiceRemaining{" +
                "invoiceRemainingId=" + invoiceRemainingId +
                ", companyId=" + companyId +
                ", contractId=" + contractId +
                ", usage=" + usage +
                ", remaining=" + remaining +
                ", uploadDate=" + uploadDate +
                ", createDate=" + createDate +
                ", modifyDate=" + modifyDate +
                ", invoiceDate='" + invoiceDate + '\'' +
                '}';
    }
}
