/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.orm.charge.entity;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;


/**
 * @author pkliu
 */
@Entity
@Table(name = "log_parameter")
public class LogParameterEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

    /**
     * log_pattern
     */
    @Column(name = "log_pattern")
    protected java.lang.String logPattern;

    /**
     * action_name
     */
    @Column(name = "action_name")
    protected java.lang.String actionName;

    /**
     * parameter_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "parameter_id", unique = true, nullable = false)
    protected java.lang.Integer parameterId;


    /**
     * 002
     *
     * @return java.lang.String logPattern
     */
    public java.lang.String getLogPattern() {
        return this.logPattern;
    }

    /**
     * 0001
     *
     * @param data Set the logPattern
     */
    public void setLogPattern(java.lang.String data) {
        this.logPattern = data;
    }

    /**
     * 002
     *
     * @return java.lang.String actionName
     */
    public java.lang.String getActionName() {
        return this.actionName;
    }

    /**
     * 0001
     *
     * @param data Set the actionName
     */
    public void setActionName(java.lang.String data) {
        this.actionName = data;
    }

    /**
     * 002
     *
     * @return java.lang.Integer parameterId
     */
    public java.lang.Integer getParameterId() {
        return this.parameterId;
    }

    /**
     * 0001
     *
     * @param data Set the parameterId
     */
    public void setParameterId(java.lang.Integer data) {
        this.parameterId = data;    //zzz
    }


    /**
     *
     */
    public LogParameterEntity() {
    }

    /**
     * full constructor
     *
     * @param logPattern
     * @param actionName
     * @param parameterId
     */
    public LogParameterEntity(
            java.lang.String logPattern
            , java.lang.String actionName
            , java.lang.Integer parameterId
    ) {
        this.setLogPattern(logPattern);
        this.setActionName(actionName);
        this.setParameterId(parameterId);
    }

    @Override
    public int hashCode() {

        return Objects.hash(logPattern, actionName, parameterId);
    }

    @Override
    public String toString() {
        return "LogParameterEntity{" +
                "logPattern='" + logPattern + '\'' +
                ", actionName='" + actionName + '\'' +
                ", parameterId=" + parameterId +
                '}';
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     *
     * @return true is equal, false is not equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof LogParameterEntity))
            return false;

        LogParameterEntity key = (LogParameterEntity) obj;
        if (this.parameterId != key.parameterId)
            return false;

        return true;
    }

}