/*
 * This file is generated by jOOQ.
 */
package com.gateweb.orm.charge.entity;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(name = "company", schema = "public", indexes = {
        @Index(name = "company_pkey", unique = true, columnList = "company_id ASC")
})
public class SimpleCompany implements Serializable {

    private static final long serialVersionUID = 2142170046;

    private Integer companyId;
    private Integer parentId;
    private String name;
    private String businessNo;
    private Integer companyType;
    private Integer verifyStatus;
    private String codeName;
    private String phone;
    private String fax;
    private String taxNo;
    private Integer transferType;
    private String email_1;
    private String email_2;

    public SimpleCompany() {
    }

    public SimpleCompany(SimpleCompany value) {
        this.companyId = value.companyId;
        this.parentId = value.parentId;
        this.name = value.name;
        this.businessNo = value.businessNo;
        this.companyType = value.companyType;
        this.verifyStatus = value.verifyStatus;
        this.codeName = value.codeName;
        this.phone = value.phone;
        this.fax = value.fax;
        this.taxNo = value.taxNo;
        this.transferType = value.transferType;
        this.email_1 = value.email_1;
        this.email_2 = value.email_2;
    }

    public SimpleCompany(Integer companyId, Integer parentId, String name, String businessNo, Integer companyType, Integer verifyStatus, String codeName, String phone, String fax, String taxNo, Integer transferType, String email_1, String email_2) {
        this.companyId = companyId;
        this.parentId = parentId;
        this.name = name;
        this.businessNo = businessNo;
        this.companyType = companyType;
        this.verifyStatus = verifyStatus;
        this.codeName = codeName;
        this.phone = phone;
        this.fax = fax;
        this.taxNo = taxNo;
        this.transferType = transferType;
        this.email_1 = email_1;
        this.email_2 = email_2;
    }

    @Id
    @Column(name = "company_id", unique = true, nullable = false, precision = 32)
    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    @Column(name = "parent_id", precision = 32)
    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    @Column(name = "name", nullable = false, length = 80)
    @NotNull
    @Size(max = 80)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "business_no", nullable = false, length = 8)
    @NotNull
    @Size(max = 8)
    public String getBusinessNo() {
        return this.businessNo;
    }

    public void setBusinessNo(String businessNo) {
        this.businessNo = businessNo;
    }

    @Column(name = "company_type", precision = 32)
    public Integer getCompanyType() {
        return this.companyType;
    }

    public void setCompanyType(Integer companyType) {
        this.companyType = companyType;
    }

    @Column(name = "verify_status", precision = 32)
    public Integer getVerifyStatus() {
        return this.verifyStatus;
    }

    public void setVerifyStatus(Integer verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    @Column(name = "code_name", length = 10)
    @Size(max = 10)
    public String getCodeName() {
        return this.codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    @Column(name = "phone", length = 50)
    @Size(max = 50)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "fax", length = 50)
    @Size(max = 50)
    public String getFax() {
        return this.fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    @Column(name = "tax_no", length = 9)
    @Size(max = 9)
    public String getTaxNo() {
        return this.taxNo;
    }

    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }

    @Column(name = "transfer_type", precision = 32)
    public Integer getTransferType() {
        return this.transferType;
    }

    public void setTransferType(Integer transferType) {
        this.transferType = transferType;
    }

    @Column(name = "email_1", length = 100)
    @Size(max = 100)
    public String getEmail_1() {
        return this.email_1;
    }

    public void setEmail_1(String email_1) {
        this.email_1 = email_1;
    }

    @Column(name = "email_2", length = 100)
    @Size(max = 100)
    public String getEmail_2() {
        return this.email_2;
    }

    public void setEmail_2(String email_2) {
        this.email_2 = email_2;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Company (");

        sb.append(companyId);
        sb.append(", ").append(parentId);
        sb.append(", ").append(name);
        sb.append(", ").append(businessNo);
        sb.append(", ").append(companyType);
        sb.append(", ").append(verifyStatus);
        sb.append(", ").append(codeName);
        sb.append(", ").append(phone);
        sb.append(", ").append(fax);
        sb.append(", ").append(taxNo);
        sb.append(", ").append(transferType);
        sb.append(", ").append(email_1);
        sb.append(", ").append(email_2);

        sb.append(")");
        return sb.toString();
    }
}
