/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 *
 * @author pkliu
 *
 */
@Entity
@Table(name = "cash_detail")
public class CashDetailEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

	/**
	 * no_tax_inclusive_price
	 */
	@Column(name = "no_tax_inclusive_price")
	protected java.math.BigDecimal noTaxInclusivePrice;
	
	/**
	 * tax_price
	 */
	@Column(name = "tax_price")
	protected java.math.BigDecimal taxPrice;
	
	/**
	 * package_id
	 */
	@Column(name = "package_id")
	protected java.lang.Integer packageId;
	
	/**
	 * tax_rate
	 */
	@Column(name = "tax_rate")
	protected java.lang.Float taxRate;
	
	/**
	 * cash_type
	 */
	@Column(name = "cash_type")
	protected java.lang.Integer cashType;
	
	/**
	 * bill_type
	 */
	@Column(name = "bill_type")
	protected java.lang.Integer billType;
	
	/**
	 * cal_ym
	 */
	@Column(name = "cal_ym")
	protected java.lang.String calYm;
	
	/**
	 * create_date
	 */
	@Column(name = "create_date")
	protected java.sql.Timestamp createDate;
	
	/**
	 * bill_id
	 */
	@Column(name = "bill_id")
	protected java.lang.Integer billId;
	
	/**
	 * company_id
	 */
	@Column(name = "company_id")
	protected java.lang.Integer companyId;
	
	/**
	 * commission_amount
	 */
	@Column(name = "commission_amount")
	protected java.math.BigDecimal commissionAmount;
	
	/**
	 * is_first
	 */
	@Column(name = "is_first")
	protected java.lang.String isFirst;
	
	/**
	 * diff_price_note
	 */
	@Column(name = "diff_price_note")
	protected java.lang.String diffPriceNote;
	
	/**
	 * commission_log_id
	 */
	@Column(name = "commission_log_id")
	protected java.lang.Integer commissionLogId;
	
	/**
	 * tax_inclusive_price
	 */
	@Column(name = "tax_inclusive_price")
	protected java.math.BigDecimal taxInclusivePrice;
	
	/**
	 * cash_master_id
	 */
	@Column(name = "cash_master_id")
	protected java.lang.Integer cashMasterId;
	
	/**
	 * tax_type
	 */
	@Column(name = "tax_type")
	protected java.lang.String taxType;
	
	/**
	 * out_ym
	 */
	@Column(name = "out_ym")
	protected java.lang.String outYm;
	
	/**
	 * creator_id
	 */
	@Column(name = "creator_id")
	protected java.lang.Integer creatorId;
	
	/**
	 * modifier_id
	 */
	@Column(name = "modifier_id")
	protected java.lang.Integer modifierId;
	
    /**
     * cash_detail_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "cash_detail_id", unique = true, nullable = false)
	protected java.lang.Integer cashDetailId;
	
	/**
	 * modify_date
	 */
	@Column(name = "modify_date")
	protected java.sql.Timestamp modifyDate;
	
	/**
	 * org_price
	 */
	@Column(name = "org_price")
	protected java.math.BigDecimal orgPrice;
	
	/**
	 * diff_price
	 */
	@Column(name = "diff_price")
	protected java.math.BigDecimal diffPrice;
	
	/**
	 * status
	 */
	@Column(name = "status")
	protected java.lang.Integer status;
	



    
	/**
	 * 002
	 * @return java.math.BigDecimal noTaxInclusivePrice
	 */
	public java.math.BigDecimal getNoTaxInclusivePrice() {
		return this.noTaxInclusivePrice;
	}
	
	/** 0001
	 * @param data Set the noTaxInclusivePrice
	 */	
	public void setNoTaxInclusivePrice(java.math.BigDecimal data) {
		this.noTaxInclusivePrice = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal taxPrice
	 */
	public java.math.BigDecimal getTaxPrice() {
		return this.taxPrice;
	}
	
	/** 0001
	 * @param data Set the taxPrice
	 */	
	public void setTaxPrice(java.math.BigDecimal data) {
		this.taxPrice = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer packageId
	 */
	public java.lang.Integer getPackageId() {
		return this.packageId;
	}
	
	/** 0001
	 * @param data Set the packageId
	 */	
	public void setPackageId(java.lang.Integer data) {
		this.packageId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Float taxRate
	 */
	public java.lang.Float getTaxRate() {
		return this.taxRate;
	}
	
	/** 0001
	 * @param data Set the taxRate
	 */	
	public void setTaxRate(java.lang.Float data) {
		this.taxRate = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer cashType
	 */
	public java.lang.Integer getCashType() {
		return this.cashType;
	}
	
	/** 0001
	 * @param data Set the cashType
	 */	
	public void setCashType(java.lang.Integer data) {
		this.cashType = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer billType
	 */
	public java.lang.Integer getBillType() {
		return this.billType;
	}
	
	/** 0001
	 * @param data Set the billType
	 */	
	public void setBillType(java.lang.Integer data) {
		this.billType = data;
	}	
	/**
	 * 002
	 * @return java.lang.String calYm
	 */
	public java.lang.String getCalYm() {
		return this.calYm;
	}
	
	/** 0001
	 * @param data Set the calYm
	 */	
	public void setCalYm(java.lang.String data) {
		this.calYm = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp createDate
	 */
	public java.sql.Timestamp getCreateDate() {
		return this.createDate;
	}
	
	/** 0001
	 * @param data Set the createDate
	 */	
	public void setCreateDate(java.sql.Timestamp data) {
		this.createDate = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer billId
	 */
	public java.lang.Integer getBillId() {
		return this.billId;
	}
	
	/** 0001
	 * @param data Set the billId
	 */	
	public void setBillId(java.lang.Integer data) {
		this.billId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer companyId
	 */
	public java.lang.Integer getCompanyId() {
		return this.companyId;
	}
	
	/** 0001
	 * @param data Set the companyId
	 */	
	public void setCompanyId(java.lang.Integer data) {
		this.companyId = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal commissionAmount
	 */
	public java.math.BigDecimal getCommissionAmount() {
		return this.commissionAmount;
	}
	
	/** 0001
	 * @param data Set the commissionAmount
	 */	
	public void setCommissionAmount(java.math.BigDecimal data) {
		this.commissionAmount = data;
	}	
	/**
	 * 002
	 * @return java.lang.String isFirst
	 */
	public java.lang.String getIsFirst() {
		return this.isFirst;
	}
	
	/** 0001
	 * @param data Set the isFirst
	 */	
	public void setIsFirst(java.lang.String data) {
		this.isFirst = data;
	}	
	/**
	 * 002
	 * @return java.lang.String diffPriceNote
	 */
	public java.lang.String getDiffPriceNote() {
		return this.diffPriceNote;
	}
	
	/** 0001
	 * @param data Set the diffPriceNote
	 */	
	public void setDiffPriceNote(java.lang.String data) {
		this.diffPriceNote = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer commissionLogId
	 */
	public java.lang.Integer getCommissionLogId() {
		return this.commissionLogId;
	}
	
	/** 0001
	 * @param data Set the commissionLogId
	 */	
	public void setCommissionLogId(java.lang.Integer data) {
		this.commissionLogId = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal taxInclusivePrice
	 */
	public java.math.BigDecimal getTaxInclusivePrice() {
		return this.taxInclusivePrice;
	}
	
	/** 0001
	 * @param data Set the taxInclusivePrice
	 */	
	public void setTaxInclusivePrice(java.math.BigDecimal data) {
		this.taxInclusivePrice = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer cashMasterId
	 */
	public java.lang.Integer getCashMasterId() {
		return this.cashMasterId;
	}
	
	/** 0001
	 * @param data Set the cashMasterId
	 */	
	public void setCashMasterId(java.lang.Integer data) {
		this.cashMasterId = data;
	}	
	/**
	 * 002
	 * @return java.lang.String taxType
	 */
	public java.lang.String getTaxType() {
		return this.taxType;
	}
	
	/** 0001
	 * @param data Set the taxType
	 */	
	public void setTaxType(java.lang.String data) {
		this.taxType = data;
	}	
	/**
	 * 002
	 * @return java.lang.String outYm
	 */
	public java.lang.String getOutYm() {
		return this.outYm;
	}
	
	/** 0001
	 * @param data Set the outYm
	 */	
	public void setOutYm(java.lang.String data) {
		this.outYm = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer creatorId
	 */
	public java.lang.Integer getCreatorId() {
		return this.creatorId;
	}
	
	/** 0001
	 * @param data Set the creatorId
	 */	
	public void setCreatorId(java.lang.Integer data) {
		this.creatorId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer modifierId
	 */
	public java.lang.Integer getModifierId() {
		return this.modifierId;
	}
	
	/** 0001
	 * @param data Set the modifierId
	 */	
	public void setModifierId(java.lang.Integer data) {
		this.modifierId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer cashDetailId
	 */
	public java.lang.Integer getCashDetailId() {
		return this.cashDetailId;
	}
	
	/** 0001
	 * @param data Set the cashDetailId
	 */	
	public void setCashDetailId(java.lang.Integer data) {
		this.cashDetailId = data;    //zzz
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp modifyDate
	 */
	public java.sql.Timestamp getModifyDate() {
		return this.modifyDate;
	}
	
	/** 0001
	 * @param data Set the modifyDate
	 */	
	public void setModifyDate(java.sql.Timestamp data) {
		this.modifyDate = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal orgPrice
	 */
	public java.math.BigDecimal getOrgPrice() {
		return this.orgPrice;
	}
	
	/** 0001
	 * @param data Set the orgPrice
	 */	
	public void setOrgPrice(java.math.BigDecimal data) {
		this.orgPrice = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal diffPrice
	 */
	public java.math.BigDecimal getDiffPrice() {
		return this.diffPrice;
	}
	
	/** 0001
	 * @param data Set the diffPrice
	 */	
	public void setDiffPrice(java.math.BigDecimal data) {
		this.diffPrice = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer status
	 */
	public java.lang.Integer getStatus() {
		return this.status;
	}
	
	/** 0001
	 * @param data Set the status
	 */	
	public void setStatus(java.lang.Integer data) {
		this.status = data;
	}	



	/**
	 *
	 */
	public CashDetailEntity(){
	}

	/**
	 * full constructor 
	 * @param noTaxInclusivePrice 
	 * @param taxPrice 
	 * @param packageId 
	 * @param taxRate 
	 * @param cashType 
	 * @param billType 
	 * @param calYm 
	 * @param createDate 
	 * @param billId 
	 * @param companyId 
	 * @param commissionAmount 
	 * @param isFirst 
	 * @param diffPriceNote 
	 * @param commissionLogId 
	 * @param taxInclusivePrice 
	 * @param cashMasterId 
	 * @param taxType 
	 * @param outYm 
	 * @param creatorId 
	 * @param modifierId 
	 * @param cashDetailId 
	 * @param modifyDate 
	 * @param orgPrice 
	 * @param diffPrice 
	 * @param status 
	 */
	public CashDetailEntity (
		 java.math.BigDecimal noTaxInclusivePrice 
		, java.math.BigDecimal taxPrice 
		, java.lang.Integer packageId 
		, java.lang.Float taxRate 
		, java.lang.Integer cashType 
		, java.lang.Integer billType 
		, java.lang.String calYm 
		, java.sql.Timestamp createDate 
		, java.lang.Integer billId 
		, java.lang.Integer companyId 
		, java.math.BigDecimal commissionAmount 
		, java.lang.String isFirst 
		, java.lang.String diffPriceNote 
		, java.lang.Integer commissionLogId 
		, java.math.BigDecimal taxInclusivePrice 
		, java.lang.Integer cashMasterId 
		, java.lang.String taxType 
		, java.lang.String outYm 
		, java.lang.Integer creatorId 
		, java.lang.Integer modifierId 
		, java.lang.Integer cashDetailId 
		, java.sql.Timestamp modifyDate 
		, java.math.BigDecimal orgPrice 
		, java.math.BigDecimal diffPrice 
		, java.lang.Integer status 
        ) {
		this.setNoTaxInclusivePrice(noTaxInclusivePrice);
		this.setTaxPrice(taxPrice);
		this.setPackageId(packageId);
		this.setTaxRate(taxRate);
		this.setCashType(cashType);
		this.setBillType(billType);
		this.setCalYm(calYm);
		this.setCreateDate(createDate);
		this.setBillId(billId);
		this.setCompanyId(companyId);
		this.setCommissionAmount(commissionAmount);
		this.setIsFirst(isFirst);
		this.setDiffPriceNote(diffPriceNote);
		this.setCommissionLogId(commissionLogId);
		this.setTaxInclusivePrice(taxInclusivePrice);
		this.setCashMasterId(cashMasterId);
		this.setTaxType(taxType);
		this.setOutYm(outYm);
		this.setCreatorId(creatorId);
		this.setModifierId(modifierId);
		this.setCashDetailId(cashDetailId);
		this.setModifyDate(modifyDate);
		this.setOrgPrice(orgPrice);
		this.setDiffPrice(diffPrice);
		this.setStatus(status);
    }

	
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public String toString() {
		 //return ToStringBuilder.reflectionToString(this , ToStringStyle.MULTI_LINE_STYLE);  
		 return new ToStringBuilder(this)
		.append("noTaxInclusivePrice", this.noTaxInclusivePrice)
		.append("taxPrice", this.taxPrice)
		.append("packageId", this.packageId)
		.append("taxRate", this.taxRate)
		.append("cashType", this.cashType)
		.append("billType", this.billType)
		.append("calYm", this.calYm)
		.append("createDate", this.createDate)
		.append("billId", this.billId)
		.append("companyId", this.companyId)
		.append("commissionAmount", this.commissionAmount)
		.append("isFirst", this.isFirst)
		.append("diffPriceNote", this.diffPriceNote)
		.append("commissionLogId", this.commissionLogId)
		.append("taxInclusivePrice", this.taxInclusivePrice)
		.append("cashMasterId", this.cashMasterId)
		.append("taxType", this.taxType)
		.append("outYm", this.outYm)
		.append("creatorId", this.creatorId)
		.append("modifierId", this.modifierId)
		.append("cashDetailId", this.cashDetailId)
		.append("modifyDate", this.modifyDate)
		.append("orgPrice", this.orgPrice)
		.append("diffPrice", this.diffPrice)
		.append("status", this.status)
		.toString();
	}	 

	/*
    @Override
	public boolean equals(Object object) {
		if (object == null || !(object instanceof CashDetailEntity))
			return false;
		EqualsBuilder builder = new EqualsBuilder();
		builder.append(this.id, ((CashDetailEntity) object).id);
		return builder.isEquals();
	}*/
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * @return true is equal, false is not equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null || !(obj instanceof CashDetailEntity))
			return false;

		CashDetailEntity key = (CashDetailEntity) obj;
		if (this.cashDetailId != key.cashDetailId ) 
        	return false;

		return true;
    }

}