/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 *
 * @author pkliu
 *
 */
@Entity
@Table(name = "dealer_company")
public class DealerCompanyEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

	/**
	 * dealer_company_name
	 */
	@Column(name = "dealer_company_name")
	protected java.lang.String dealerCompanyName;
	
    /**
     * dealer_company_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "dealer_company_id", unique = true, nullable = false)
	protected java.lang.Integer dealerCompanyId;
	
	/**
	 * business_no
	 */
	@Column(name = "business_no")
	protected java.lang.String businessNo;
	
	/**
	 * collect_money
	 */
	@Column(name = "collect_money")
	protected java.math.BigDecimal collectMoney;
	
	/**
	 * company_address
	 */
	@Column(name = "company_address")
	protected java.lang.String companyAddress;
	
	/**
	 * main_amount
	 */
	@Column(name = "main_amount")
	protected java.math.BigDecimal mainAmount;
	
	/**
	 * main_percent
	 */
	@Column(name = "main_percent")
	protected java.math.BigDecimal mainPercent;
	
	/**
	 * phone
	 */
	@Column(name = "phone")
	protected java.lang.String phone;
	
	/**
	 * creator_id
	 */
	@Column(name = "creator_id")
	protected java.lang.Integer creatorId;
	
	/**
	 * modifier_id
	 */
	@Column(name = "modifier_id")
	protected java.lang.Integer modifierId;
	
	/**
	 * create_date
	 */
	@Column(name = "create_date")
	protected java.sql.Timestamp createDate;
	
	/**
	 * fax
	 */
	@Column(name = "fax")
	protected java.lang.String fax;
	
	/**
	 * modify_date
	 */
	@Column(name = "modify_date")
	protected java.sql.Timestamp modifyDate;
	
	/**
	 * addition_percent
	 */
	@Column(name = "addition_percent")
	protected java.math.BigDecimal additionPercent;
	
	/**
	 * commission_type
	 */
	@Column(name = "commission_type")
	protected java.lang.String commissionType;
	
	/**
	 * email
	 */
	@Column(name = "email")
	protected java.lang.String email;
	
	/**
	 * status
	 */
	@Column(name = "status")
	protected java.lang.Integer status;
	



    
	/**
	 * 002
	 * @return java.lang.String dealerCompanyName
	 */
	public java.lang.String getDealerCompanyName() {
		return this.dealerCompanyName;
	}
	
	/** 0001
	 * @param data Set the dealerCompanyName
	 */	
	public void setDealerCompanyName(java.lang.String data) {
		this.dealerCompanyName = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer dealerCompanyId
	 */
	public java.lang.Integer getDealerCompanyId() {
		return this.dealerCompanyId;
	}
	
	/** 0001
	 * @param data Set the dealerCompanyId
	 */	
	public void setDealerCompanyId(java.lang.Integer data) {
		this.dealerCompanyId = data;    //zzz
	}	
	/**
	 * 002
	 * @return java.lang.String businessNo
	 */
	public java.lang.String getBusinessNo() {
		return this.businessNo;
	}
	
	/** 0001
	 * @param data Set the businessNo
	 */	
	public void setBusinessNo(java.lang.String data) {
		this.businessNo = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal collectMoney
	 */
	public java.math.BigDecimal getCollectMoney() {
		return this.collectMoney;
	}
	
	/** 0001
	 * @param data Set the collectMoney
	 */	
	public void setCollectMoney(java.math.BigDecimal data) {
		this.collectMoney = data;
	}	
	/**
	 * 002
	 * @return java.lang.String companyAddress
	 */
	public java.lang.String getCompanyAddress() {
		return this.companyAddress;
	}
	
	/** 0001
	 * @param data Set the companyAddress
	 */	
	public void setCompanyAddress(java.lang.String data) {
		this.companyAddress = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal mainAmount
	 */
	public java.math.BigDecimal getMainAmount() {
		return this.mainAmount;
	}
	
	/** 0001
	 * @param data Set the mainAmount
	 */	
	public void setMainAmount(java.math.BigDecimal data) {
		this.mainAmount = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal mainPercent
	 */
	public java.math.BigDecimal getMainPercent() {
		return this.mainPercent;
	}
	
	/** 0001
	 * @param data Set the mainPercent
	 */	
	public void setMainPercent(java.math.BigDecimal data) {
		this.mainPercent = data;
	}	
	/**
	 * 002
	 * @return java.lang.String phone
	 */
	public java.lang.String getPhone() {
		return this.phone;
	}
	
	/** 0001
	 * @param data Set the phone
	 */	
	public void setPhone(java.lang.String data) {
		this.phone = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer creatorId
	 */
	public java.lang.Integer getCreatorId() {
		return this.creatorId;
	}
	
	/** 0001
	 * @param data Set the creatorId
	 */	
	public void setCreatorId(java.lang.Integer data) {
		this.creatorId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer modifierId
	 */
	public java.lang.Integer getModifierId() {
		return this.modifierId;
	}
	
	/** 0001
	 * @param data Set the modifierId
	 */	
	public void setModifierId(java.lang.Integer data) {
		this.modifierId = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp createDate
	 */
	public java.sql.Timestamp getCreateDate() {
		return this.createDate;
	}
	
	/** 0001
	 * @param data Set the createDate
	 */	
	public void setCreateDate(java.sql.Timestamp data) {
		this.createDate = data;
	}	
	/**
	 * 002
	 * @return java.lang.String fax
	 */
	public java.lang.String getFax() {
		return this.fax;
	}
	
	/** 0001
	 * @param data Set the fax
	 */	
	public void setFax(java.lang.String data) {
		this.fax = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp modifyDate
	 */
	public java.sql.Timestamp getModifyDate() {
		return this.modifyDate;
	}
	
	/** 0001
	 * @param data Set the modifyDate
	 */	
	public void setModifyDate(java.sql.Timestamp data) {
		this.modifyDate = data;
	}	
	/**
	 * 002
	 * @return java.math.BigDecimal additionPercent
	 */
	public java.math.BigDecimal getAdditionPercent() {
		return this.additionPercent;
	}
	
	/** 0001
	 * @param data Set the additionPercent
	 */	
	public void setAdditionPercent(java.math.BigDecimal data) {
		this.additionPercent = data;
	}	
	/**
	 * 002
	 * @return java.lang.String commissionType
	 */
	public java.lang.String getCommissionType() {
		return this.commissionType;
	}
	
	/** 0001
	 * @param data Set the commissionType
	 */	
	public void setCommissionType(java.lang.String data) {
		this.commissionType = data;
	}	
	/**
	 * 002
	 * @return java.lang.String email
	 */
	public java.lang.String getEmail() {
		return this.email;
	}
	
	/** 0001
	 * @param data Set the email
	 */	
	public void setEmail(java.lang.String data) {
		this.email = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer status
	 */
	public java.lang.Integer getStatus() {
		return this.status;
	}
	
	/** 0001
	 * @param data Set the status
	 */	
	public void setStatus(java.lang.Integer data) {
		this.status = data;
	}	



	/**
	 *
	 */
	public DealerCompanyEntity(){
	}

	/**
	 * full constructor 
	 * @param dealerCompanyName 
	 * @param dealerCompanyId 
	 * @param businessNo 
	 * @param collectMoney 
	 * @param companyAddress 
	 * @param mainAmount 
	 * @param mainPercent 
	 * @param phone 
	 * @param creatorId 
	 * @param modifierId 
	 * @param createDate 
	 * @param fax 
	 * @param modifyDate 
	 * @param additionPercent 
	 * @param commissionType 
	 * @param email 
	 * @param status 
	 */
	public DealerCompanyEntity (
		 java.lang.String dealerCompanyName 
		, java.lang.Integer dealerCompanyId 
		, java.lang.String businessNo 
		, java.math.BigDecimal collectMoney 
		, java.lang.String companyAddress 
		, java.math.BigDecimal mainAmount 
		, java.math.BigDecimal mainPercent 
		, java.lang.String phone 
		, java.lang.Integer creatorId 
		, java.lang.Integer modifierId 
		, java.sql.Timestamp createDate 
		, java.lang.String fax 
		, java.sql.Timestamp modifyDate 
		, java.math.BigDecimal additionPercent 
		, java.lang.String commissionType 
		, java.lang.String email 
		, java.lang.Integer status 
        ) {
		this.setDealerCompanyName(dealerCompanyName);
		this.setDealerCompanyId(dealerCompanyId);
		this.setBusinessNo(businessNo);
		this.setCollectMoney(collectMoney);
		this.setCompanyAddress(companyAddress);
		this.setMainAmount(mainAmount);
		this.setMainPercent(mainPercent);
		this.setPhone(phone);
		this.setCreatorId(creatorId);
		this.setModifierId(modifierId);
		this.setCreateDate(createDate);
		this.setFax(fax);
		this.setModifyDate(modifyDate);
		this.setAdditionPercent(additionPercent);
		this.setCommissionType(commissionType);
		this.setEmail(email);
		this.setStatus(status);
    }

	
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public String toString() {
		 //return ToStringBuilder.reflectionToString(this , ToStringStyle.MULTI_LINE_STYLE);  
		 return new ToStringBuilder(this)
		.append("dealerCompanyName", this.dealerCompanyName)
		.append("dealerCompanyId", this.dealerCompanyId)
		.append("businessNo", this.businessNo)
		.append("collectMoney", this.collectMoney)
		.append("companyAddress", this.companyAddress)
		.append("mainAmount", this.mainAmount)
		.append("mainPercent", this.mainPercent)
		.append("phone", this.phone)
		.append("creatorId", this.creatorId)
		.append("modifierId", this.modifierId)
		.append("createDate", this.createDate)
		.append("fax", this.fax)
		.append("modifyDate", this.modifyDate)
		.append("additionPercent", this.additionPercent)
		.append("commissionType", this.commissionType)
		.append("email", this.email)
		.append("status", this.status)
		.toString();
	}	 

	/*
    @Override
	public boolean equals(Object object) {
		if (object == null || !(object instanceof DealerCompanyEntity))
			return false;
		EqualsBuilder builder = new EqualsBuilder();
		builder.append(this.id, ((DealerCompanyEntity) object).id);
		return builder.isEquals();
	}*/
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * @return true is equal, false is not equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null || !(obj instanceof DealerCompanyEntity))
			return false;

		DealerCompanyEntity key = (DealerCompanyEntity) obj;
		if (this.dealerCompanyId != key.dealerCompanyId ) 
        	return false;

		return true;
    }

}