/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 *
 * @author pkliu
 *
 */
@Entity
@Table(name = "log_data")
public class LogDataEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

	/**
	 * session_obj
	 */
	@Column(name = "session_obj")
	protected java.lang.String sessionObj;
	
    /**
     * log_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "log_id", unique = true, nullable = false)
	protected java.lang.Integer logId;
	
	/**
	 * user_name
	 */
	@Column(name = "user_name")
	protected java.lang.String userName;
	
	/**
	 * request_obj
	 */
	@Column(name = "request_obj")
	protected java.lang.String requestObj;
	
	/**
	 * log_url
	 */
	@Column(name = "log_url")
	protected java.lang.String logUrl;
	
	/**
	 * parameter_id
	 */
	@Column(name = "parameter_id")
	protected java.lang.Integer parameterId;
	
	/**
	 * access_time
	 */
	@Column(name = "access_time")
	protected java.sql.Timestamp accessTime;
	



    
	/**
	 * 002
	 * @return java.lang.String sessionObj
	 */
	public java.lang.String getSessionObj() {
		return this.sessionObj;
	}
	
	/** 0001
	 * @param data Set the sessionObj
	 */	
	public void setSessionObj(java.lang.String data) {
		this.sessionObj = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer logId
	 */
	public java.lang.Integer getLogId() {
		return this.logId;
	}
	
	/** 0001
	 * @param data Set the logId
	 */	
	public void setLogId(java.lang.Integer data) {
		this.logId = data;    //zzz
	}	
	/**
	 * 002
	 * @return java.lang.String userName
	 */
	public java.lang.String getUserName() {
		return this.userName;
	}
	
	/** 0001
	 * @param data Set the userName
	 */	
	public void setUserName(java.lang.String data) {
		this.userName = data;
	}	
	/**
	 * 002
	 * @return java.lang.String requestObj
	 */
	public java.lang.String getRequestObj() {
		return this.requestObj;
	}
	
	/** 0001
	 * @param data Set the requestObj
	 */	
	public void setRequestObj(java.lang.String data) {
		this.requestObj = data;
	}	
	/**
	 * 002
	 * @return java.lang.String logUrl
	 */
	public java.lang.String getLogUrl() {
		return this.logUrl;
	}
	
	/** 0001
	 * @param data Set the logUrl
	 */	
	public void setLogUrl(java.lang.String data) {
		this.logUrl = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer parameterId
	 */
	public java.lang.Integer getParameterId() {
		return this.parameterId;
	}
	
	/** 0001
	 * @param data Set the parameterId
	 */	
	public void setParameterId(java.lang.Integer data) {
		this.parameterId = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp accessTime
	 */
	public java.sql.Timestamp getAccessTime() {
		return this.accessTime;
	}
	
	/** 0001
	 * @param data Set the accessTime
	 */	
	public void setAccessTime(java.sql.Timestamp data) {
		this.accessTime = data;
	}	



	/**
	 *
	 */
	public LogDataEntity(){
	}

	/**
	 * full constructor 
	 * @param sessionObj 
	 * @param logId 
	 * @param userName 
	 * @param requestObj 
	 * @param logUrl 
	 * @param parameterId 
	 * @param accessTime 
	 */
	public LogDataEntity (
		 java.lang.String sessionObj 
		, java.lang.Integer logId 
		, java.lang.String userName 
		, java.lang.String requestObj 
		, java.lang.String logUrl 
		, java.lang.Integer parameterId 
		, java.sql.Timestamp accessTime 
        ) {
		this.setSessionObj(sessionObj);
		this.setLogId(logId);
		this.setUserName(userName);
		this.setRequestObj(requestObj);
		this.setLogUrl(logUrl);
		this.setParameterId(parameterId);
		this.setAccessTime(accessTime);
    }

	
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public String toString() {
		 //return ToStringBuilder.reflectionToString(this , ToStringStyle.MULTI_LINE_STYLE);  
		 return new ToStringBuilder(this)
		.append("sessionObj", this.sessionObj)
		.append("logId", this.logId)
		.append("userName", this.userName)
		.append("requestObj", this.requestObj)
		.append("logUrl", this.logUrl)
		.append("parameterId", this.parameterId)
		.append("accessTime", this.accessTime)
		.toString();
	}	 

	/*
    @Override
	public boolean equals(Object object) {
		if (object == null || !(object instanceof LogDataEntity))
			return false;
		EqualsBuilder builder = new EqualsBuilder();
		builder.append(this.id, ((LogDataEntity) object).id);
		return builder.isEquals();
	}*/
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * @return true is equal, false is not equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null || !(obj instanceof LogDataEntity))
			return false;

		LogDataEntity key = (LogDataEntity) obj;
		if (this.logId != key.logId ) 
        	return false;

		return true;
    }

}