/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:15 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


/**
 *
 * @author pkliu
 *
 */
@Entity
@Table(name = "package_mode")
public class PackageModeEntity implements Serializable {

//long serialVersionUID jdk tool: serialver.exe 

	/**
	 * addition_id
	 */
	@Column(name = "addition_id")
	protected java.lang.Integer additionId;
	
	/**
	 * broker2
	 */
	@Column(name = "broker2")
	protected java.lang.String broker2;
	
	/**
	 * broker_cp3
	 */
	@Column(name = "broker_cp3")
	protected java.lang.String brokerCp3;
	
	/**
	 * dealer_company_id
	 */
	@Column(name = "dealer_company_id")
	protected java.lang.Integer dealerCompanyId;
	
	/**
	 * broker3
	 */
	@Column(name = "broker3")
	protected java.lang.String broker3;
	
	/**
	 * company_id
	 */
	@Column(name = "company_id")
	protected java.lang.Integer companyId;
	
    /**
     * package_id java.lang.Integer , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "package_id", unique = true, nullable = false)
	protected java.lang.Integer packageId;
	
	/**
	 * package_type
	 */
	@Column(name = "package_type")
	protected java.lang.Integer packageType;
	
	/**
	 * charge_id
	 */
	@Column(name = "charge_id")
	protected java.lang.Integer chargeId;
	
	/**
	 * creator_id
	 */
	@Column(name = "creator_id")
	protected java.lang.Integer creatorId;
	
	/**
	 * modifier_id
	 */
	@Column(name = "modifier_id")
	protected java.lang.Integer modifierId;
	
	/**
	 * create_date
	 */
	@Column(name = "create_date")
	protected java.sql.Timestamp createDate;
	
	/**
	 * modify_date
	 */
	@Column(name = "modify_date")
	protected java.sql.Timestamp modifyDate;
	
	/**
	 * dealer_id
	 */
	@Column(name = "dealer_id")
	protected java.lang.Integer dealerId;
	
	/**
	 * status
	 */
	@Column(name = "status")
	protected java.lang.String status;
	
	/**
	 * broker_cp2
	 */
	@Column(name = "broker_cp2")
	protected java.lang.String brokerCp2;
	



    
	/**
	 * 002
	 * @return java.lang.Integer additionId
	 */
	public java.lang.Integer getAdditionId() {
		return this.additionId;
	}
	
	/** 0001
	 * @param data Set the additionId
	 */	
	public void setAdditionId(java.lang.Integer data) {
		this.additionId = data;
	}	
	/**
	 * 002
	 * @return java.lang.String broker2
	 */
	public java.lang.String getBroker2() {
		return this.broker2;
	}
	
	/** 0001
	 * @param data Set the broker2
	 */	
	public void setBroker2(java.lang.String data) {
		this.broker2 = data;
	}	
	/**
	 * 002
	 * @return java.lang.String brokerCp3
	 */
	public java.lang.String getBrokerCp3() {
		return this.brokerCp3;
	}
	
	/** 0001
	 * @param data Set the brokerCp3
	 */	
	public void setBrokerCp3(java.lang.String data) {
		this.brokerCp3 = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer dealerCompanyId
	 */
	public java.lang.Integer getDealerCompanyId() {
		return this.dealerCompanyId;
	}
	
	/** 0001
	 * @param data Set the dealerCompanyId
	 */	
	public void setDealerCompanyId(java.lang.Integer data) {
		this.dealerCompanyId = data;
	}	
	/**
	 * 002
	 * @return java.lang.String broker3
	 */
	public java.lang.String getBroker3() {
		return this.broker3;
	}
	
	/** 0001
	 * @param data Set the broker3
	 */	
	public void setBroker3(java.lang.String data) {
		this.broker3 = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer companyId
	 */
	public java.lang.Integer getCompanyId() {
		return this.companyId;
	}
	
	/** 0001
	 * @param data Set the companyId
	 */	
	public void setCompanyId(java.lang.Integer data) {
		this.companyId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer packageId
	 */
	public java.lang.Integer getPackageId() {
		return this.packageId;
	}
	
	/** 0001
	 * @param data Set the packageId
	 */	
	public void setPackageId(java.lang.Integer data) {
		this.packageId = data;    //zzz
	}	
	/**
	 * 002
	 * @return java.lang.Integer packageType
	 */
	public java.lang.Integer getPackageType() {
		return this.packageType;
	}
	
	/** 0001
	 * @param data Set the packageType
	 */	
	public void setPackageType(java.lang.Integer data) {
		this.packageType = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer chargeId
	 */
	public java.lang.Integer getChargeId() {
		return this.chargeId;
	}
	
	/** 0001
	 * @param data Set the chargeId
	 */	
	public void setChargeId(java.lang.Integer data) {
		this.chargeId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer creatorId
	 */
	public java.lang.Integer getCreatorId() {
		return this.creatorId;
	}
	
	/** 0001
	 * @param data Set the creatorId
	 */	
	public void setCreatorId(java.lang.Integer data) {
		this.creatorId = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer modifierId
	 */
	public java.lang.Integer getModifierId() {
		return this.modifierId;
	}
	
	/** 0001
	 * @param data Set the modifierId
	 */	
	public void setModifierId(java.lang.Integer data) {
		this.modifierId = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp createDate
	 */
	public java.sql.Timestamp getCreateDate() {
		return this.createDate;
	}
	
	/** 0001
	 * @param data Set the createDate
	 */	
	public void setCreateDate(java.sql.Timestamp data) {
		this.createDate = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp modifyDate
	 */
	public java.sql.Timestamp getModifyDate() {
		return this.modifyDate;
	}
	
	/** 0001
	 * @param data Set the modifyDate
	 */	
	public void setModifyDate(java.sql.Timestamp data) {
		this.modifyDate = data;
	}	
	/**
	 * 002
	 * @return java.lang.Integer dealerId
	 */
	public java.lang.Integer getDealerId() {
		return this.dealerId;
	}
	
	/** 0001
	 * @param data Set the dealerId
	 */	
	public void setDealerId(java.lang.Integer data) {
		this.dealerId = data;
	}	
	/**
	 * 002
	 * @return java.lang.String status
	 */
	public java.lang.String getStatus() {
		return this.status;
	}
	
	/** 0001
	 * @param data Set the status
	 */	
	public void setStatus(java.lang.String data) {
		this.status = data;
	}	
	/**
	 * 002
	 * @return java.lang.String brokerCp2
	 */
	public java.lang.String getBrokerCp2() {
		return this.brokerCp2;
	}
	
	/** 0001
	 * @param data Set the brokerCp2
	 */	
	public void setBrokerCp2(java.lang.String data) {
		this.brokerCp2 = data;
	}	



	/**
	 *
	 */
	public PackageModeEntity(){
	}

	/**
	 * full constructor 
	 * @param additionId 
	 * @param broker2 
	 * @param brokerCp3 
	 * @param dealerCompanyId 
	 * @param broker3 
	 * @param companyId 
	 * @param packageId 
	 * @param packageType 
	 * @param chargeId 
	 * @param creatorId 
	 * @param modifierId 
	 * @param createDate 
	 * @param modifyDate 
	 * @param dealerId 
	 * @param status 
	 * @param brokerCp2 
	 */
	public PackageModeEntity (
		 java.lang.Integer additionId 
		, java.lang.String broker2 
		, java.lang.String brokerCp3 
		, java.lang.Integer dealerCompanyId 
		, java.lang.String broker3 
		, java.lang.Integer companyId 
		, java.lang.Integer packageId 
		, java.lang.Integer packageType 
		, java.lang.Integer chargeId 
		, java.lang.Integer creatorId 
		, java.lang.Integer modifierId 
		, java.sql.Timestamp createDate 
		, java.sql.Timestamp modifyDate 
		, java.lang.Integer dealerId 
		, java.lang.String status 
		, java.lang.String brokerCp2 
        ) {
		this.setAdditionId(additionId);
		this.setBroker2(broker2);
		this.setBrokerCp3(brokerCp3);
		this.setDealerCompanyId(dealerCompanyId);
		this.setBroker3(broker3);
		this.setCompanyId(companyId);
		this.setPackageId(packageId);
		this.setPackageType(packageType);
		this.setChargeId(chargeId);
		this.setCreatorId(creatorId);
		this.setModifierId(modifierId);
		this.setCreateDate(createDate);
		this.setModifyDate(modifyDate);
		this.setDealerId(dealerId);
		this.setStatus(status);
		this.setBrokerCp2(brokerCp2);
    }

	
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public String toString() {
		 //return ToStringBuilder.reflectionToString(this , ToStringStyle.MULTI_LINE_STYLE);  
		 return new ToStringBuilder(this)
		.append("additionId", this.additionId)
		.append("broker2", this.broker2)
		.append("brokerCp3", this.brokerCp3)
		.append("dealerCompanyId", this.dealerCompanyId)
		.append("broker3", this.broker3)
		.append("companyId", this.companyId)
		.append("packageId", this.packageId)
		.append("packageType", this.packageType)
		.append("chargeId", this.chargeId)
		.append("creatorId", this.creatorId)
		.append("modifierId", this.modifierId)
		.append("createDate", this.createDate)
		.append("modifyDate", this.modifyDate)
		.append("dealerId", this.dealerId)
		.append("status", this.status)
		.append("brokerCp2", this.brokerCp2)
		.toString();
	}	 

	/*
    @Override
	public boolean equals(Object object) {
		if (object == null || !(object instanceof PackageModeEntity))
			return false;
		EqualsBuilder builder = new EqualsBuilder();
		builder.append(this.id, ((PackageModeEntity) object).id);
		return builder.isEquals();
	}*/
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * @return true is equal, false is not equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null || !(obj instanceof PackageModeEntity))
			return false;

		PackageModeEntity key = (PackageModeEntity) obj;
		if (this.packageId != key.packageId ) 
        	return false;

		return true;
    }

}