/*
 * $Header: $
 * This java source file is generated by pkliu on Fri Aug 11 14:13:12 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.turnkey.repository; 
    
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;
import org.springframework.stereotype.Repository;

import com.gateweb.turnkey.model.TaskConfig;
import com.gateweb.turnkey.model.TaskConfigKeys;
import com.meshinnovation.db.dao.exception.DaoSystemException;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of TaskConfig
 */
@Repository("taskConfigRepository")
public interface TaskConfigRepository extends JpaRepository<TaskConfig, TaskConfigKeys>
	, QueryDslPredicateExecutor<TaskConfig> ,TaskConfigRepositoryCustom {
	
	void deleteById(TaskConfigKeys id) throws DaoSystemException;
	
	Long deleteByIdTask(String task);
	
	Long deleteByIdCategoryType(String categoryType);

	Long deleteByIdProcessType(String processType);

	public TaskConfig findById(TaskConfigKeys id);
	
	public Page<TaskConfig> findById(TaskConfigKeys id, Pageable pageable);
	
	public boolean exists(TaskConfigKeys id);
	
	public List<TaskConfig> findAll();
	
	@Query(value="select * from task_config limit 100", nativeQuery=true)
	public List<TaskConfig> findTop100();
	
	public List<TaskConfig> findByIdTask(String task);
	
	public List<TaskConfig> findByIdCategoryType(String categoryType);
	
	public List<TaskConfig> findByIdProcessType(String processType);
	
	public List<TaskConfig> findTop100ByIdTask(String task);
	
	public List<TaskConfig> findTop100ByIdCategoryType(String categoryType);
	
	public List<TaskConfig> findTop100ByIdProcessType(String processType);
	
	public long count();

			
}

	