/*
 * $Header: $
 * This java source file is generated by pkliu on Fri Aug 11 14:13:12 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.turnkey.repository; 
    
import java.sql.SQLException;
import java.util.Collection;
import com.gateweb.turnkey.*;
import com.gateweb.turnkey.model.*;
import com.meshinnovation.db.dao.exception.DaoSystemException;
import java.io.Serializable;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of TurnkeyMessageLogDetail
 */
 @Repository("turnkeyMessageLogDetailRepository")
public interface TurnkeyMessageLogDetailRepository extends JpaRepository<TurnkeyMessageLogDetail, TurnkeyMessageLogDetailKeys>
	, QueryDslPredicateExecutor<TurnkeyMessageLogDetail> ,TurnkeyMessageLogDetailRepositoryCustom {
	

	void deleteById(TurnkeyMessageLogDetailKeys id) throws DaoSystemException;
	
	Long deleteByIdTask(String task);
	
	Long deleteByIdSeqno(String seqno);

	Long deleteByIdSubseqno(String subseqno);

	public TurnkeyMessageLogDetail findById(TurnkeyMessageLogDetailKeys id);
	
	public Page<TurnkeyMessageLogDetail> findById(TurnkeyMessageLogDetailKeys id, Pageable pageable);
	
	public boolean exists(TurnkeyMessageLogDetailKeys id);
	
	public List<TurnkeyMessageLogDetail> findAll();
	
	public List<TurnkeyMessageLogDetail> findTop100ByIdTask(String task);
	
	public List<TurnkeyMessageLogDetail> findTop100ByIdSeqno(String seqno);

	public List<TurnkeyMessageLogDetail> findTop100ByIdSubseqno(String subseqno);
	
	public long count();
	
	public List<TurnkeyMessageLogDetail> findByIdTask(String task);
	
	public List<TurnkeyMessageLogDetail> findByIdSeqno(String seqno);

	public List<TurnkeyMessageLogDetail> findByIdSubseqno(String subseqno);

			
}

	