/*
 * $Header: $
 * This java source file is generated by pkliu on Fri Aug 11 14:13:12 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.turnkey.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.meshinnovation.db.model.BaseObject;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 *
 * @author pkliu
 *
 */
@Entity
@Table(name = "outgoinginvoice")
public class Outgoinginvoice extends BaseObject{

//long serialVersionUID jdk tool: serialver.exe 

	/**
	 * seller
	 */
	@Column(name = "seller")
	protected java.lang.String seller;
	
	/**
	 * feedbackmessage
	 */
	@Column(name = "feedbackmessage")
	protected java.lang.String feedbackmessage;
	
	/**
	 * inserttime
	 */
	@Column(name = "inserttime")
	protected java.sql.Timestamp inserttime;
	
	/**
	 * locktime
	 */
	@Column(name = "locktime")
	protected java.sql.Timestamp locktime;
	
	/**
	 * conversationid
	 */
	@Column(name = "conversationid")
	protected java.lang.String conversationid;
	
	/**
	 * centerstatus
	 */
	@Column(name = "centerstatus")
	protected java.lang.String centerstatus;
	
	/**
	 * contenttype
	 */
	@Column(name = "contenttype")
	protected java.lang.String contenttype;
	
	/**
	 * buyer
	 */
	@Column(name = "buyer")
	protected java.lang.String buyer;
	
	/**
	 * senttime
	 */
	@Column(name = "senttime")
	protected java.sql.Timestamp senttime;
	
	/**
	 * acktime
	 */
	@Column(name = "acktime")
	protected java.sql.Timestamp acktime;
	
	/**
	 * xmlfilename
	 */
	@Column(name = "xmlfilename")
	protected java.lang.String xmlfilename;
	
	/**
	 * completetime
	 */
	@Column(name = "completetime")
	protected java.sql.Timestamp completetime;
	
    /**
     * invoiceid java.lang.String , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "invoiceid", unique = true, nullable = false)
	protected java.lang.String invoiceid;
	
	/**
	 * centerstatusdesc
	 */
	@Column(name = "centerstatusdesc")
	protected java.lang.String centerstatusdesc;
	
	/**
	 * invoicenumber
	 */
	@Column(name = "invoicenumber")
	protected java.lang.String invoicenumber;
	
	/**
	 * status
	 */
	@Column(name = "status")
	protected java.lang.String status;
	



    
	/**
	 * 002
	 * @return java.lang.String seller
	 */
	public java.lang.String getSeller() {
		return this.seller;
	}
	
	/** 0001
	 * @param data Set the seller
	 */	
	public void setSeller(java.lang.String data) {
		this.seller = data;
	}	
	/**
	 * 002
	 * @return java.lang.String feedbackmessage
	 */
	public java.lang.String getFeedbackmessage() {
		return this.feedbackmessage;
	}
	
	/** 0001
	 * @param data Set the feedbackmessage
	 */	
	public void setFeedbackmessage(java.lang.String data) {
		this.feedbackmessage = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp inserttime
	 */
	public java.sql.Timestamp getInserttime() {
		return this.inserttime;
	}
	
	/** 0001
	 * @param data Set the inserttime
	 */	
	public void setInserttime(java.sql.Timestamp data) {
		this.inserttime = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp locktime
	 */
	public java.sql.Timestamp getLocktime() {
		return this.locktime;
	}
	
	/** 0001
	 * @param data Set the locktime
	 */	
	public void setLocktime(java.sql.Timestamp data) {
		this.locktime = data;
	}	
	/**
	 * 002
	 * @return java.lang.String conversationid
	 */
	public java.lang.String getConversationid() {
		return this.conversationid;
	}
	
	/** 0001
	 * @param data Set the conversationid
	 */	
	public void setConversationid(java.lang.String data) {
		this.conversationid = data;
	}	
	/**
	 * 002
	 * @return java.lang.String centerstatus
	 */
	public java.lang.String getCenterstatus() {
		return this.centerstatus;
	}
	
	/** 0001
	 * @param data Set the centerstatus
	 */	
	public void setCenterstatus(java.lang.String data) {
		this.centerstatus = data;
	}	
	/**
	 * 002
	 * @return java.lang.String contenttype
	 */
	public java.lang.String getContenttype() {
		return this.contenttype;
	}
	
	/** 0001
	 * @param data Set the contenttype
	 */	
	public void setContenttype(java.lang.String data) {
		this.contenttype = data;
	}	
	/**
	 * 002
	 * @return java.lang.String buyer
	 */
	public java.lang.String getBuyer() {
		return this.buyer;
	}
	
	/** 0001
	 * @param data Set the buyer
	 */	
	public void setBuyer(java.lang.String data) {
		this.buyer = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp senttime
	 */
	public java.sql.Timestamp getSenttime() {
		return this.senttime;
	}
	
	/** 0001
	 * @param data Set the senttime
	 */	
	public void setSenttime(java.sql.Timestamp data) {
		this.senttime = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp acktime
	 */
	public java.sql.Timestamp getAcktime() {
		return this.acktime;
	}
	
	/** 0001
	 * @param data Set the acktime
	 */	
	public void setAcktime(java.sql.Timestamp data) {
		this.acktime = data;
	}	
	/**
	 * 002
	 * @return java.lang.String xmlfilename
	 */
	public java.lang.String getXmlfilename() {
		return this.xmlfilename;
	}
	
	/** 0001
	 * @param data Set the xmlfilename
	 */	
	public void setXmlfilename(java.lang.String data) {
		this.xmlfilename = data;
	}	
	/**
	 * 002
	 * @return java.sql.Timestamp completetime
	 */
	public java.sql.Timestamp getCompletetime() {
		return this.completetime;
	}
	
	/** 0001
	 * @param data Set the completetime
	 */	
	public void setCompletetime(java.sql.Timestamp data) {
		this.completetime = data;
	}	
	/**
	 * 002
	 * @return java.lang.String invoiceid
	 */
	public java.lang.String getInvoiceid() {
		return this.invoiceid;
	}
	
	/** 0001
	 * @param data Set the invoiceid
	 */	
	public void setInvoiceid(java.lang.String data) {
		this.invoiceid = data;    //zzz
	}	
	/**
	 * 002
	 * @return java.lang.String centerstatusdesc
	 */
	public java.lang.String getCenterstatusdesc() {
		return this.centerstatusdesc;
	}
	
	/** 0001
	 * @param data Set the centerstatusdesc
	 */	
	public void setCenterstatusdesc(java.lang.String data) {
		this.centerstatusdesc = data;
	}	
	/**
	 * 002
	 * @return java.lang.String invoicenumber
	 */
	public java.lang.String getInvoicenumber() {
		return this.invoicenumber;
	}
	
	/** 0001
	 * @param data Set the invoicenumber
	 */	
	public void setInvoicenumber(java.lang.String data) {
		this.invoicenumber = data;
	}	
	/**
	 * 002
	 * @return java.lang.String status
	 */
	public java.lang.String getStatus() {
		return this.status;
	}
	
	/** 0001
	 * @param data Set the status
	 */	
	public void setStatus(java.lang.String data) {
		this.status = data;
	}	



	/**
	 *
	 */
	public Outgoinginvoice(){
	}

	/**
	 * full constructor 
	 * @param seller 
	 * @param feedbackmessage 
	 * @param inserttime 
	 * @param locktime 
	 * @param conversationid 
	 * @param centerstatus 
	 * @param contenttype 
	 * @param buyer 
	 * @param senttime 
	 * @param acktime 
	 * @param xmlfilename 
	 * @param completetime 
	 * @param invoiceid 
	 * @param centerstatusdesc 
	 * @param invoicenumber 
	 * @param status 
	 */
	public Outgoinginvoice (
		 java.lang.String seller 
		, java.lang.String feedbackmessage 
		, java.sql.Timestamp inserttime 
		, java.sql.Timestamp locktime 
		, java.lang.String conversationid 
		, java.lang.String centerstatus 
		, java.lang.String contenttype 
		, java.lang.String buyer 
		, java.sql.Timestamp senttime 
		, java.sql.Timestamp acktime 
		, java.lang.String xmlfilename 
		, java.sql.Timestamp completetime 
		, java.lang.String invoiceid 
		, java.lang.String centerstatusdesc 
		, java.lang.String invoicenumber 
		, java.lang.String status 
        ) {
		this.setSeller(seller);
		this.setFeedbackmessage(feedbackmessage);
		this.setInserttime(inserttime);
		this.setLocktime(locktime);
		this.setConversationid(conversationid);
		this.setCenterstatus(centerstatus);
		this.setContenttype(contenttype);
		this.setBuyer(buyer);
		this.setSenttime(senttime);
		this.setAcktime(acktime);
		this.setXmlfilename(xmlfilename);
		this.setCompletetime(completetime);
		this.setInvoiceid(invoiceid);
		this.setCenterstatusdesc(centerstatusdesc);
		this.setInvoicenumber(invoicenumber);
		this.setStatus(status);
    }

	
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public String toString() {
		 //return ToStringBuilder.reflectionToString(this , ToStringStyle.MULTI_LINE_STYLE);  
		 return new ToStringBuilder(this)
		.append("seller", this.seller)
		.append("feedbackmessage", this.feedbackmessage)
		.append("inserttime", this.inserttime)
		.append("locktime", this.locktime)
		.append("conversationid", this.conversationid)
		.append("centerstatus", this.centerstatus)
		.append("contenttype", this.contenttype)
		.append("buyer", this.buyer)
		.append("senttime", this.senttime)
		.append("acktime", this.acktime)
		.append("xmlfilename", this.xmlfilename)
		.append("completetime", this.completetime)
		.append("invoiceid", this.invoiceid)
		.append("centerstatusdesc", this.centerstatusdesc)
		.append("invoicenumber", this.invoicenumber)
		.append("status", this.status)
		.toString();
	}	 

	/*
    @Override
	public boolean equals(Object object) {
		if (object == null || !(object instanceof Outgoinginvoice))
			return false;
		EqualsBuilder builder = new EqualsBuilder();
		builder.append(this.id, ((Outgoinginvoice) object).id);
		return builder.isEquals();
	}*/
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * @return true is equal, false is not equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null || !(obj instanceof Outgoinginvoice))
			return false;

		Outgoinginvoice key = (Outgoinginvoice) obj;
		if (this.invoiceid != key.invoiceid ) 
        	return false;

		return true;
    }

}