/*
 * $Header: $
 * This java source file is generated by pkliu on Fri Aug 11 14:13:12 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.turnkey.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.GenerationType.AUTO;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.meshinnovation.db.model.BaseObject;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 *
 * @author pkliu
 *
 */
@Entity
@Table(name = "turnkey_sequence")
public class TurnkeySequence extends BaseObject{

//long serialVersionUID jdk tool: serialver.exe 

    /**
     * sequence java.lang.String , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sequence", unique = true, nullable = false)
	protected java.lang.String sequence;
	



    
	/**
	 * 002
	 * @return java.lang.String sequence
	 */
	public java.lang.String getSequence() {
		return this.sequence;
	}
	
	/** 0001
	 * @param data Set the sequence
	 */	
	public void setSequence(java.lang.String data) {
		this.sequence = data;    //zzz
	}	



	/**
	 *
	 */
	public TurnkeySequence(){
	}

	/**
	 * full constructor 
	 * @param sequence 
	 */
	public TurnkeySequence (
		 java.lang.String sequence 
        ) {
		this.setSequence(sequence);
    }

	
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public String toString() {
		 //return ToStringBuilder.reflectionToString(this , ToStringStyle.MULTI_LINE_STYLE);  
		 return new ToStringBuilder(this)
		.append("sequence", this.sequence)
		.toString();
	}	 

	/*
    @Override
	public boolean equals(Object object) {
		if (object == null || !(object instanceof TurnkeySequence))
			return false;
		EqualsBuilder builder = new EqualsBuilder();
		builder.append(this.id, ((TurnkeySequence) object).id);
		return builder.isEquals();
	}*/
	
	/**
	 * Indicates whether some other object is "equal to" this one.
	 * @return true is equal, false is not equal
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;

		if (obj == null || !(obj instanceof TurnkeySequence))
			return false;

		TurnkeySequence key = (TurnkeySequence) obj;
		if (this.sequence != key.sequence ) 
        	return false;

		return true;
    }

}