/*
 * $Header: $
 * This java source file is generated by pkliu on Thu Aug 03 11:22:57 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.einv.exception;

import com.gateweb.base.exception.ApplicationException;

/**
 * @author pkliu
 *
 */
public class EinvFacadeException extends ApplicationException {

	/**
	 * 
	 */
	public EinvFacadeException() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param message
	 */
	public EinvFacadeException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param cause
	 */
	public EinvFacadeException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param message
	 * @param cause
	 */
	public EinvFacadeException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

}
