/*
 * $Header: $
 * This java source file is generated by pkliu on Thu Aug 03 11:22:57 CST 2017
 * For more information, please contact pkliu@meshinnovation.com
 */
package com.gateweb.einv.service.impl;
import java.util.List;
import java.util.Optional;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.gateweb.einv.exception.EinvSysException;
import com.gateweb.einv.model.Company;
import com.gateweb.einv.model.InvoiceDetails;
import com.gateweb.einv.model.InvoiceMain;
import com.gateweb.einv.model.User;
import com.gateweb.einv.repository.EinvCompanyRepository;
import com.gateweb.einv.repository.InvoiceDetails2Repository;
import com.gateweb.einv.repository.EinvInvoiceMainRepository;
import com.gateweb.einv.repository.EinvUserRepository;
import com.gateweb.einv.service.EinvFacade;
/**
 * @author pkliu
 *
 */
@Service("einvFacade") 
public class EinvFacadeImpl implements EinvFacade {

	/**
	* <p><code>Log</code> instance for this application. </p>
	*/
	private Log log = LogFactory.getLog(this.getClass().getName());
	
	
	/**
	 * InvoiceMainRepository
	 */
	@Autowired
	@Qualifier("invoiceMain2Repository")
	private EinvInvoiceMainRepository invoiceMain2Repository = null;
	
	
	/**
	 * CompanyRepository
	 */
	@Autowired
	@Qualifier("company2Repository")
	private EinvCompanyRepository company2Repository = null;
	
	
	/**
	 * UserRepository
	 */
	@Autowired
	@Qualifier("user2Repository")
	private EinvUserRepository user2Repository = null;
	
	
	/**
	 * InvoiceDetailsRepository
	 */
	@Autowired
	@Qualifier("invoiceDetails2Repository")
	private InvoiceDetails2Repository invoiceDetails2Repository = null;
	


	/**
	 *
	 */
	public void setInvoiceMain2Repository(EinvInvoiceMainRepository setRepository){
		this.invoiceMain2Repository = setRepository;
	}
	
	/*
	public InvoiceMain2Repository getInvoiceMain2Repository(){
		return this.invoiceMain2Repository;
	}	
	 */
	/**
	 *
	 */
	public void setCompany2Repository(EinvCompanyRepository setRepository){
		this.company2Repository = setRepository;
	}
	
	/*
	public Company2Repository getCompany2Repository(){
		return this.company2Repository;
	}	
	 */
	/**
	 *
	 */
	public void setUser2Repository(EinvUserRepository setRepository){
		this.user2Repository = setRepository;
	}
	
	/*
	public User2Repository getUser2Repository(){
		return this.user2Repository;
	}	
	 */
	/**
	 *
	 */
	public void setInvoiceDetails2Repository(InvoiceDetails2Repository setRepository){
		this.invoiceDetails2Repository = setRepository;
	}
	
	/*
	public InvoiceDetails2Repository getInvoiceDetails2Repository(){
		return this.invoiceDetails2Repository;
	}	
	 */
	/**
	 *
	 *
	 */
	public EinvFacadeImpl(){
	}

    /**
     * Create a new record in Database.
     * @exception    EinvSysException if something is wrong.
     */
	public InvoiceMain save(InvoiceMain bean) {

		log.debug("EinvFacadeImpl create InvoiceMain  before dao save InvoiceMain :  "+bean);	
		return invoiceMain2Repository.save(bean); 
		//log.debug("EinvFacadeImpl create InvoiceMain   successfully.");		
	}

    /**
     * Retrieve a record from Database.
     * @param	id
     */
	public InvoiceMain findInvoiceMainById(
		java.lang.Long invoiceId 
	) {
		Optional<InvoiceMain> data = null;
		log.debug("EinvFacadeImpl findInvoiceMainById begin :" 
			+"invoiceId = "+ invoiceId
		);	
		try {
			data = invoiceMain2Repository.findById(invoiceId);	
			if(data.isPresent()) {
				return data.get();
			}
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
		
		log.debug("EinvFacadeImpl findInvoiceMainById successfully.");	
		return null;
	}

    /**
     * Retrieve all records from Database.
     * @exception       EinvSysException if something is wrong.
     */
    public List<InvoiceMain> findInvoiceMainAll() {
		log.debug("EinvFacadeImpl searchInvoiceMainAll  before dao get all ");	

		List<InvoiceMain> results = null;
		results = invoiceMain2Repository.findAll();
		log.debug("EinvFacadeImpl searchInvoiceMainAll   successfully.");	
		return results;
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @exception    EinvSysException if something is wrong.
     */
    public InvoiceMain update(InvoiceMain bean) {
		log.debug("EinvFacadeImpl update InvoiceMain   before dao update : bean "+bean);	
		return invoiceMain2Repository.save(bean);
		//log.debug("EinvFacadeImpl update InvoiceMain    successfully.");	

	}

    /**
     * Delete a new record in Database.
     */
	public void deleteInvoiceMain(
		java.lang.Long invoiceId 
	) {

			log.debug("EinvFacadeImpl deleteInvoiceMain   delete :" 
				+"invoiceId = "+ invoiceId
			);			
			invoiceMain2Repository.deleteById(
				invoiceId 
			);
			 
		log.debug("EinvFacadeImpl deleteInvoiceMain   successfully. ");	
	} 

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<InvoiceMain> searchBy(InvoiceMain bean) {
		log.debug("EinvFacadeImpl searchWith InvoiceMain   before dao searchWith : bean "+bean);	
		List<InvoiceMain> results = null;
		results = invoiceMain2Repository.searchWithVo(bean);	
		log.debug("EinvFacadeImpl searchWithInvoiceMain   successfully. ");	
		return results;
    }

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<InvoiceMain> searchLike(InvoiceMain bean) {
		log.debug("EinvFacadeImpl searchLike InvoiceMain   before dao searchLike : bean "+bean);	
		List<InvoiceMain> results = null;
		results = invoiceMain2Repository.searchLikeVo(bean);
		log.debug("EinvFacadeImpl searchLikeInvoiceMain   successfully. ");	
		return results;
    }
    /**
     * Create a new record in Database.
     * @exception    EinvSysException if something is wrong.
     */
	public Company save(Company bean) {

		log.debug("EinvFacadeImpl create Company  before dao save Company :  "+bean);	
		return company2Repository.save(bean); 
		//log.debug("EinvFacadeImpl create Company   successfully.");		
	}

    /**
     * Retrieve a record from Database.
     * @param	id
     */
	public Company findCompanyById(
		java.lang.Long companyId 
	) {
		Optional<Company> data = null;
		log.debug("EinvFacadeImpl findCompanyById begin :" 
			+"companyId = "+ companyId
		);	
		try {
			data = company2Repository.findById(companyId);	
			if(data.isPresent()) {
				return data.get();
			}
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
		
		log.debug("EinvFacadeImpl findCompanyById successfully.");	
		return null;
	}

    /**
     * Retrieve all records from Database.
     * @exception       EinvSysException if something is wrong.
     */
    public List<Company> findCompanyAll() {
		log.debug("EinvFacadeImpl searchCompanyAll  before dao get all ");	

		List<Company> results = null;
		results = company2Repository.findAll();
		log.debug("EinvFacadeImpl searchCompanyAll   successfully.");	
		return results;
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @exception    EinvSysException if something is wrong.
     */
    public Company update(Company bean) {
		log.debug("EinvFacadeImpl update Company   before dao update : bean "+bean);	
		return company2Repository.save(bean);
		//log.debug("EinvFacadeImpl update Company    successfully.");	

	}

    /**
     * Delete a new record in Database.
     */
	public void deleteCompany(
		java.lang.Long companyId 
	) {

			log.debug("EinvFacadeImpl deleteCompany   delete :" 
				+"companyId = "+ companyId
			);			
			company2Repository.deleteById(
				companyId 
			);
			 
		log.debug("EinvFacadeImpl deleteCompany   successfully. ");	
	} 

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<Company> searchBy(Company bean) {
		log.debug("EinvFacadeImpl searchWith Company   before dao searchWith : bean "+bean);	
		List<Company> results = null;
		results = company2Repository.searchWithVo(bean);	
		log.debug("EinvFacadeImpl searchWithCompany   successfully. ");	
		return results;
    }

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<Company> searchLike(Company bean) {
		log.debug("EinvFacadeImpl searchLike Company   before dao searchLike : bean "+bean);	
		List<Company> results = null;
		results = company2Repository.searchLikeVo(bean);
		log.debug("EinvFacadeImpl searchLikeCompany   successfully. ");	
		return results;
    }
    /**
     * Create a new record in Database.
     * @exception    EinvSysException if something is wrong.
     */
	public User save(User bean) {

		log.debug("EinvFacadeImpl create User  before dao save User :  "+bean);	
		return user2Repository.save(bean); 
		//log.debug("EinvFacadeImpl create User   successfully.");		
	}

    /**
     * Retrieve a record from Database.
     * @param	id
     */
	public User findUserById(
		java.lang.Long userId 
	) {
		Optional<User> data = null;
		log.debug("EinvFacadeImpl findUserById begin :" 
			+"userId = "+ userId
		);	
		try {
			data = user2Repository.findById(userId);	
			if(data.isPresent()) {
				return data.get();
			}
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
		
		log.debug("EinvFacadeImpl findUserById successfully.");	
		return null;
	}

    /**
     * Retrieve all records from Database.
     * @exception       EinvSysException if something is wrong.
     */
    public List<User> findUserAll() {
		log.debug("EinvFacadeImpl searchUserAll  before dao get all ");	

		List<User> results = null;
		results = user2Repository.findAll();
		log.debug("EinvFacadeImpl searchUserAll   successfully.");	
		return results;
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @exception    EinvSysException if something is wrong.
     */
    public User update(User bean) {
		log.debug("EinvFacadeImpl update User   before dao update : bean "+bean);	
		return user2Repository.save(bean);
		//log.debug("EinvFacadeImpl update User    successfully.");	

	}

    /**
     * Delete a new record in Database.
     */
	public void deleteUser(
		java.lang.Long userId 
	) {

			log.debug("EinvFacadeImpl deleteUser   delete :" 
				+"userId = "+ userId
			);			
			user2Repository.deleteById(
				userId 
			);
			 
		log.debug("EinvFacadeImpl deleteUser   successfully. ");	
	} 

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<User> searchBy(User bean) {
		log.debug("EinvFacadeImpl searchWith User   before dao searchWith : bean "+bean);	
		List<User> results = null;
		results = user2Repository.searchWithVo(bean);	
		log.debug("EinvFacadeImpl searchWithUser   successfully. ");	
		return results;
    }

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<User> searchLike(User bean) {
		log.debug("EinvFacadeImpl searchLike User   before dao searchLike : bean "+bean);	
		List<User> results = null;
		results = user2Repository.searchLikeVo(bean);
		log.debug("EinvFacadeImpl searchLikeUser   successfully. ");	
		return results;
    }

    /**
     * Create a new record in Database.
     * @exception    EinvSysException if something is wrong.
     */
	public InvoiceDetails save(InvoiceDetails bean) {

		log.debug("EinvFacadeImpl create InvoiceDetails  before dao save InvoiceDetails :  "+bean);	
		return invoiceDetails2Repository.save(bean); 
		//log.debug("EinvFacadeImpl create InvoiceDetails   successfully.");		
	}

    /**
     * Retrieve a record from Database.
     * @param	id
     */
	public InvoiceDetails findInvoiceDetailsById(
		java.lang.Long invoiceDetailsId 
	) {
		Optional<InvoiceDetails> data = null;
		log.debug("EinvFacadeImpl findUserById begin :" 
			+"invoiceDetailsId = "+ invoiceDetailsId
		);	
		try {
			data = invoiceDetails2Repository.findById(invoiceDetailsId);	
			if(data.isPresent()) {
				return data.get();
			}
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
		
		log.debug("EinvFacadeImpl findUserById successfully.");	
		return null;
	}

    /**
     * Retrieve all records from Database.
     * @exception       EinvSysException if something is wrong.
     */
    public List<InvoiceDetails> findInvoiceDetailsAll() {
		log.debug("EinvFacadeImpl searchInvoiceDetailsAll  before dao get all ");	

		List<InvoiceDetails> results = null;
		results = invoiceDetails2Repository.findAll();
		log.debug("EinvFacadeImpl searchInvoiceDetailsAll   successfully.");	
		return results;
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @exception    EinvSysException if something is wrong.
     */
    public InvoiceDetails update(InvoiceDetails bean) {
		log.debug("EinvFacadeImpl update InvoiceDetails   before dao update : bean "+bean);	
		return invoiceDetails2Repository.save(bean);
		//log.debug("EinvFacadeImpl update InvoiceDetails    successfully.");	

	}

    /**
     * Delete a new record in Database.
     */
	public void deleteInvoiceDetails(
		java.lang.Long invoiceDetailsId 
	) {

			log.debug("EinvFacadeImpl deleteInvoiceDetails   delete :" 
				+"invoiceDetailsId = "+ invoiceDetailsId
			);			
			invoiceDetails2Repository.deleteById(
				invoiceDetailsId 
			);
			 
		log.debug("EinvFacadeImpl deleteInvoiceDetails   successfully. ");	
	} 

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<InvoiceDetails> searchBy(InvoiceDetails bean) {
		log.debug("EinvFacadeImpl searchWith InvoiceDetails   before dao searchWith : bean "+bean);	
		List<InvoiceDetails> results = null;
		results = invoiceDetails2Repository.searchWithVo(bean);	
		log.debug("EinvFacadeImpl searchWithInvoiceDetails   successfully. ");	
		return results;
    }

    /**
     * search records from Database.
     * @param bean   The Object search criteria
     */
    public List<InvoiceDetails> searchLike(InvoiceDetails bean) {
		log.debug("EinvFacadeImpl searchLike InvoiceDetails   before dao searchLike : bean "+bean);	
		List<InvoiceDetails> results = null;
		results = invoiceDetails2Repository.searchLikeVo(bean);
		log.debug("EinvFacadeImpl searchLikeInvoiceDetails   successfully. ");	
		return results;
    }
    
 
}
