/*
 * $Header: $
 * This java source file is generated by pkliu on Fri Aug 11 14:13:12 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.turnkey.repository.impl; 
//import org.springframework.orm.ObjectRetrievalFailureException;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;

import com.gateweb.turnkey.model.QTurnkeySequence;
import com.gateweb.turnkey.model.TurnkeySequence;
import com.gateweb.turnkey.repository.TurnkeySequenceRepository;
import com.gateweb.turnkey.repository.TurnkeySequenceRepositoryCustom;
import com.google.common.collect.Lists;
import com.querydsl.core.BooleanBuilder;


/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of TurnkeySequence
 */
//@Repository("turnkeySequenceRepositoryCustom")
public class TurnkeySequenceRepositoryImpl implements TurnkeySequenceRepositoryCustom {
	
	/**
	 * <p>
	 * <code>Log</code> instance for this application.
	 * </p>
	 */
	protected final Log log = LogFactory.getLog(getClass());
	
	/*	@PersistenceContext
	private EntityManager em;

	public void setEntityManager(EntityManager em) {
		this.em = em;
	}*/

	@Autowired
	TurnkeySequenceRepository turnkeySequenceRepository;
	
	public TurnkeySequenceRepositoryImpl(){
	}
	

	@SuppressWarnings("unchecked")
	public List<TurnkeySequence> searchWithVo(TurnkeySequence vo) {
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QTurnkeySequence turnkeySequence = QTurnkeySequence.turnkeySequence;

		if ( vo.getSequence() != null && !"".equals(vo.getSequence())) {
			builder.and(turnkeySequence.sequence.equalsIgnoreCase(vo.getSequence())); //java.lang.String
		}
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(turnkeySequenceRepository.findAll(builder.getValue()));	
	}
	
	@SuppressWarnings("unchecked")
	public List<TurnkeySequence> searchWithVo(TurnkeySequence vo, Pageable pageable) {
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QTurnkeySequence turnkeySequence = QTurnkeySequence.turnkeySequence;

		if ( vo.getSequence() != null && !"".equals(vo.getSequence())) {
			builder.and(turnkeySequence.sequence.equalsIgnoreCase(vo.getSequence())); //java.lang.String
		}
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(turnkeySequenceRepository.findAll(builder.getValue(), pageable));	
	}
	
	@SuppressWarnings("unchecked")
	public List<TurnkeySequence> searchWithVo(TurnkeySequence vo, int pageOffset, int pageSize) {
		Pageable pageable = new PageRequest(pageOffset, pageSize);
		return searchWithVo(vo, pageable);
	}
	
	@SuppressWarnings("unchecked")
	public List<TurnkeySequence> searchLikeVo(TurnkeySequence vo) {
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QTurnkeySequence turnkeySequence = QTurnkeySequence.turnkeySequence;

		if ( vo.getSequence() != null && !"".equals(vo.getSequence())) {
			builder.and(turnkeySequence.sequence.containsIgnoreCase(vo.getSequence())); //java.lang.String
		}
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(turnkeySequenceRepository.findAll(builder.getValue()));
	}		
	
	

	@SuppressWarnings("unchecked")
	public List<TurnkeySequence> searchLikeVo(TurnkeySequence vo, Pageable pageable) {
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo vo: " + vo);
		BooleanBuilder builder = new BooleanBuilder();
		QTurnkeySequence turnkeySequence = QTurnkeySequence.turnkeySequence;

		if ( vo.getSequence() != null && !"".equals(vo.getSequence())) {
			builder.and(turnkeySequence.sequence.containsIgnoreCase(vo.getSequence())); //java.lang.String
		}
		log.debug("TurnkeySequenceRepositoryImpl searchWithVo predicate  " + builder.getValue());
		return Lists.newArrayList(turnkeySequenceRepository.findAll(builder.getValue(), pageable));
	}	
	
	@SuppressWarnings("unchecked")
	public List<TurnkeySequence> searchLikeVo(TurnkeySequence vo, int pageOffset, int pageSize) {
		Pageable pageable = new PageRequest(pageOffset, pageSize);
		return searchLikeVo(vo, pageable);
	}
	
}
