/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.repository; 

import com.gateweb.charge.model.*;
import com.meshinnovation.db.dao.exception.DaoSystemException;
import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of DealerCompany
 */
 @Repository("dealerCompany")
public interface DealerCompanyRepository extends JpaRepository<DealerCompanyEntity, Integer>
	, QuerydslPredicateExecutor<DealerCompanyEntity> ,DealerCompanyRepositoryCustom {
	
    /**
     * Delete a record in Database.
	 * @param  dealerCompanyId
	 * @throws DaoSystemException	if system is wrong.
     */
	void deleteByDealerCompanyId(	
		java.lang.Integer dealerCompanyId 
	) throws DaoSystemException;

//	public DealerCompanyEntity findByDealerCompanyId(Long dealerCompanyId);
//	
//	public Page<DealerCompanyEntity> findByDealerCompanyId(Long dealerCompanyId, Pageable pageable);
//	
//	public boolean exists(Long dealerCompanyId);
//	
//	public List<DealerCompanyEntity> findAll();
//	
//	public List<DealerCompanyEntity> findTop100ByDealerCompanyId(Long dealerCompanyId);
//	
//	public long count();

	//取得經銷商清單(下拉選單顯示經銷商列表)
	public List<DealerCompanyEntity> findByStatus(Integer status);

	//取得某經銷商資訊
	public DealerCompanyEntity findByDealerCompanyId(Integer dealerCompanyId);

}

	