/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.charge.repository; 
    
import java.sql.SQLException;
import java.util.Collection;
import com.gateweb.charge.*;
import com.gateweb.charge.model.*;
import com.meshinnovation.db.dao.exception.DaoSystemException;
import java.io.Serializable;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * 
 * @author pkliu
 *
 * This class provides methods to populate DB Table of InvoiceMain
 */
 @Repository("invoiceMainRepository")
public interface InvoiceMainRepository extends JpaRepository<InvoiceMainEntity, Long>
	, QuerydslPredicateExecutor<InvoiceMainEntity> ,InvoiceMainRepositoryCustom {
	
    /**
     * Delete a record in Database.
	 * @param $pkVar.columnName   PK 
	 * @throws DaoSystemException	if system is wrong.
     */
	void deleteByInvoiceId(	
		java.lang.Long invoiceId 
	) throws DaoSystemException;

//	public InvoiceMainEntity findByInvoiceId(Long invoiceId);
//	
//	public Page<InvoiceMainEntity> findByInvoiceId(Long invoiceId, Pageable pageable);
//	
//	public boolean exists(Long invoiceId);
//	
//	public List<InvoiceMainEntity> findAll();
//	
//	public List<InvoiceMainEntity> findTop100ByInvoiceId(Long invoiceId);
//	
//	public long count();

	public InvoiceMainEntity findByInvoiceIdAndCYearMonth(Long invoiceId, String yearMonth);

	public InvoiceMainEntity findByInvoiceIdAndCYearMonthAndInvoiceNumber(Long invoiceId,String yearMonth,String invoiceNumber);

	public InvoiceMainEntity findByCYearMonthAndInvoiceNumber(String yearMonth,String invoiceNumber);

}

	