/*
 * This file is generated by jOOQ.
 */
package com.gateweb.charge.enumeration;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public enum ChargeBaseType {
    INVOICE_AMOUNT_SUM("發票開立數量依發票日期合計"),
//    INVOICE_AMOUNT_SUM_BY_INVOICE_DATE("發票開立數量依發票日期合計"),
    INVOICE_AMOUNT_SUM_BY_UPLOAD_DATE("發票開立數量依上傳日期合計"),
    EMAIL_AMOUNT_SUM("Email寄送數量合計");

    public final String description;

    ChargeBaseType(String desc) {
        this.description = desc;
    }
}
