package com.gateweb.charge.enumeration;

public enum NoticeType {
    PAYMENT_REQUEST_MAIL,
    PAYMENT_REQUEST_MAIL_NO_CC,
    PAYMENT_REQUEST_CORRECTION_MAIL,
    PAYMENT_REQUEST_CORRECTION_MAIL_NO_CC,
    REMAINING_COUNT_INVENTORY_ALERT_CC,
    CONTRACT_ENABLED_NOTICE
}
