/*
 * $Header: $
 * This java source file is generated by pkliu on Tue Jan 30 14:38:14 CST 2018
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.orm.charge.repository;

import com.gateweb.orm.charge.entity.CashMasterEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * @author pkliu
 * <p>
 * This class provides methods to populate DB Table of CashMaster
 */
@Repository("cashMaster")
public interface CashMasterRepository extends JpaRepository<CashMasterEntity, Integer>
        , QuerydslPredicateExecutor<CashMasterEntity> {

    List<CashMasterEntity> findByOutYm(String yearMonth);

    CashMasterEntity findByCashMasterId(Integer cashMasterId);

    List<CashMasterEntity> findByOutYmIsAndCompanyIdIs(String yearMonth, Integer companyId);

    List<CashMasterEntity> findByOutYmIsAndCompanyIdIsAndStatusIs(String yearMonth, Integer companyId, Integer status);

    List<CashMasterEntity> findByOutYmIs(String outYm);

}

	