/*
 * $Header: $
 * This java source file is generated by pkliu on Thu Aug 03 11:22:57 CST 2017
 * For more information, please contact pkliu@sysfoundry.com
 */
package com.gateweb.orm.einv.entity;

import com.meshinnovation.db.model.BaseObject;
import jdk.nashorn.internal.ir.annotations.Immutable;

import javax.persistence.*;
import java.util.Objects;

/**
 * @author pkliu
 */
@Entity
@Table(name = "company")
@Immutable
public class Company extends BaseObject {

//long serialVersionUID jdk tool: serialver.exe 

    /**
     * company_type
     */
    @Column(name = "company_type")
    protected java.lang.Long companyType;

    /**
     * code_name
     */
    @Column(name = "code_name")
    protected java.lang.String codeName;

    /**
     * company_address
     */
    @Column(name = "company_address")
    protected java.lang.String companyAddress;

    /**
     * email_2
     */
    @Column(name = "email_2")
    protected java.lang.String email2;

    /**
     * email_1
     */
    @Column(name = "email_1")
    protected java.lang.String email1;

    /**
     * tax_no
     */
    @Column(name = "tax_no")
    protected java.lang.String taxNo;

    /**
     * contact_phone1
     */
    @Column(name = "contact_phone1")
    protected java.lang.String contactPhone1;

    /**
     * contact_phone2
     */
    @Column(name = "contact_phone2")
    protected java.lang.String contactPhone2;

    /**
     * bottom_banner
     */
    @Column(name = "bottom_banner")
    protected java.lang.String bottomBanner;

    /**
     * verify_status
     */
    @Column(name = "verify_status")
    protected java.lang.Long verifyStatus;

    /**
     * fax
     */
    @Column(name = "fax")
    protected java.lang.String fax;

    /**
     * create_date
     */
    @Column(name = "create_date")
    protected java.sql.Timestamp createDate;

    /**
     * company_id java.lang.Long , PK     * @GeneratedValue(strategy = GenerationType.AUTO)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "company_id", unique = true, nullable = false)
    protected java.lang.Long companyId;

    /**
     * business_no
     */
    @Column(name = "business_no")
    protected java.lang.String businessNo;

    /**
     * company_key
     */
    @Column(name = "company_key")
    protected java.lang.String companyKey;

    /**
     * mailing_address
     */
    @Column(name = "mailing_address")
    protected java.lang.String mailingAddress;

    /**
     * phone
     */
    @Column(name = "phone")
    protected java.lang.String phone;

    /**
     * parent_id
     */
    @Column(name = "parent_id")
    protected java.lang.Long parentId;

    /**
     * name
     */
    @Column(name = "name")
    protected java.lang.String name;

    /**
     * creator_id
     */
    @Column(name = "creator_id")
    protected java.lang.Long creatorId;

    /**
     * modifier_id
     */
    @Column(name = "modifier_id")
    protected java.lang.Long modifierId;

    /**
     * tax_office
     */
    @Column(name = "tax_office")
    protected java.lang.String taxOffice;

    /**
     * top_banner
     */
    @Column(name = "top_banner")
    protected java.lang.String topBanner;

    /**
     * transfer_type
     */
    @Column(name = "transfer_type")
    protected java.lang.Long transferType;

    /**
     * contact1
     */
    @Column(name = "contact1")
    protected java.lang.String contact1;

    /**
     * modify_date
     */
    @Column(name = "modify_date")
    protected java.sql.Timestamp modifyDate;

    /**
     * contact2
     */
    @Column(name = "contact2")
    protected java.lang.String contact2;

    /**
     * city_id
     */
    @Column(name = "city_id")
    protected java.lang.Long cityId;


    /**
     * 002
     *
     * @return java.lang.Long companyType
     */
    public java.lang.Long getCompanyType() {
        return this.companyType;
    }

    /**
     * 0001
     *
     * @param data Set the companyType
     */
    public void setCompanyType(java.lang.Long data) {
        this.companyType = data;
    }

    /**
     * 002
     *
     * @return java.lang.String codeName
     */
    public java.lang.String getCodeName() {
        return this.codeName;
    }

    /**
     * 0001
     *
     * @param data Set the codeName
     */
    public void setCodeName(java.lang.String data) {
        this.codeName = data;
    }

    /**
     * 002
     *
     * @return java.lang.String companyAddress
     */
    public java.lang.String getCompanyAddress() {
        return this.companyAddress;
    }

    /**
     * 0001
     *
     * @param data Set the companyAddress
     */
    public void setCompanyAddress(java.lang.String data) {
        this.companyAddress = data;
    }

    /**
     * 002
     *
     * @return java.lang.String email2
     */
    public java.lang.String getEmail2() {
        return this.email2;
    }

    /**
     * 0001
     *
     * @param data Set the email2
     */
    public void setEmail2(java.lang.String data) {
        this.email2 = data;
    }

    /**
     * 002
     *
     * @return java.lang.String email1
     */
    public java.lang.String getEmail1() {
        return this.email1;
    }

    /**
     * 0001
     *
     * @param data Set the email1
     */
    public void setEmail1(java.lang.String data) {
        this.email1 = data;
    }

    /**
     * 002
     *
     * @return java.lang.String taxNo
     */
    public java.lang.String getTaxNo() {
        return this.taxNo;
    }

    /**
     * 0001
     *
     * @param data Set the taxNo
     */
    public void setTaxNo(java.lang.String data) {
        this.taxNo = data;
    }

    /**
     * 002
     *
     * @return java.lang.String contactPhone1
     */
    public java.lang.String getContactPhone1() {
        return this.contactPhone1;
    }

    /**
     * 0001
     *
     * @param data Set the contactPhone1
     */
    public void setContactPhone1(java.lang.String data) {
        this.contactPhone1 = data;
    }

    /**
     * 002
     *
     * @return java.lang.String contactPhone2
     */
    public java.lang.String getContactPhone2() {
        return this.contactPhone2;
    }

    /**
     * 0001
     *
     * @param data Set the contactPhone2
     */
    public void setContactPhone2(java.lang.String data) {
        this.contactPhone2 = data;
    }

    /**
     * 002
     *
     * @return java.lang.String bottomBanner
     */
    public java.lang.String getBottomBanner() {
        return this.bottomBanner;
    }

    /**
     * 0001
     *
     * @param data Set the bottomBanner
     */
    public void setBottomBanner(java.lang.String data) {
        this.bottomBanner = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long verifyStatus
     */
    public java.lang.Long getVerifyStatus() {
        return this.verifyStatus;
    }

    /**
     * 0001
     *
     * @param data Set the verifyStatus
     */
    public void setVerifyStatus(java.lang.Long data) {
        this.verifyStatus = data;
    }

    /**
     * 002
     *
     * @return java.lang.String fax
     */
    public java.lang.String getFax() {
        return this.fax;
    }

    /**
     * 0001
     *
     * @param data Set the fax
     */
    public void setFax(java.lang.String data) {
        this.fax = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp createDate
     */
    public java.sql.Timestamp getCreateDate() {
        return this.createDate;
    }

    /**
     * 0001
     *
     * @param data Set the createDate
     */
    public void setCreateDate(java.sql.Timestamp data) {
        this.createDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long companyId
     */
    public java.lang.Long getCompanyId() {
        return this.companyId;
    }

    /**
     * 0001
     *
     * @param data Set the companyId
     */
    public void setCompanyId(java.lang.Long data) {
        this.companyId = data;    //zzz
    }

    /**
     * 002
     *
     * @return java.lang.String businessNo
     */
    public java.lang.String getBusinessNo() {
        return this.businessNo;
    }

    /**
     * 0001
     *
     * @param data Set the businessNo
     */
    public void setBusinessNo(java.lang.String data) {
        this.businessNo = data;
    }

    /**
     * 002
     *
     * @return java.lang.String companyKey
     */
    public java.lang.String getCompanyKey() {
        return this.companyKey;
    }

    /**
     * 0001
     *
     * @param data Set the companyKey
     */
    public void setCompanyKey(java.lang.String data) {
        this.companyKey = data;
    }

    /**
     * 002
     *
     * @return java.lang.String mailingAddress
     */
    public java.lang.String getMailingAddress() {
        return this.mailingAddress;
    }

    /**
     * 0001
     *
     * @param data Set the mailingAddress
     */
    public void setMailingAddress(java.lang.String data) {
        this.mailingAddress = data;
    }

    /**
     * 002
     *
     * @return java.lang.String phone
     */
    public java.lang.String getPhone() {
        return this.phone;
    }

    /**
     * 0001
     *
     * @param data Set the phone
     */
    public void setPhone(java.lang.String data) {
        this.phone = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long parentId
     */
    public java.lang.Long getParentId() {
        return this.parentId;
    }

    /**
     * 0001
     *
     * @param data Set the parentId
     */
    public void setParentId(java.lang.Long data) {
        this.parentId = data;
    }

    /**
     * 002
     *
     * @return java.lang.String name
     */
    public java.lang.String getName() {
        return this.name;
    }

    /**
     * 0001
     *
     * @param data Set the name
     */
    public void setName(java.lang.String data) {
        this.name = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long creatorId
     */
    public java.lang.Long getCreatorId() {
        return this.creatorId;
    }

    /**
     * 0001
     *
     * @param data Set the creatorId
     */
    public void setCreatorId(java.lang.Long data) {
        this.creatorId = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long modifierId
     */
    public java.lang.Long getModifierId() {
        return this.modifierId;
    }

    /**
     * 0001
     *
     * @param data Set the modifierId
     */
    public void setModifierId(java.lang.Long data) {
        this.modifierId = data;
    }

    /**
     * 002
     *
     * @return java.lang.String taxOffice
     */
    public java.lang.String getTaxOffice() {
        return this.taxOffice;
    }

    /**
     * 0001
     *
     * @param data Set the taxOffice
     */
    public void setTaxOffice(java.lang.String data) {
        this.taxOffice = data;
    }

    /**
     * 002
     *
     * @return java.lang.String topBanner
     */
    public java.lang.String getTopBanner() {
        return this.topBanner;
    }

    /**
     * 0001
     *
     * @param data Set the topBanner
     */
    public void setTopBanner(java.lang.String data) {
        this.topBanner = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long transferType
     */
    public java.lang.Long getTransferType() {
        return this.transferType;
    }

    /**
     * 0001
     *
     * @param data Set the transferType
     */
    public void setTransferType(java.lang.Long data) {
        this.transferType = data;
    }

    /**
     * 002
     *
     * @return java.lang.String contact1
     */
    public java.lang.String getContact1() {
        return this.contact1;
    }

    /**
     * 0001
     *
     * @param data Set the contact1
     */
    public void setContact1(java.lang.String data) {
        this.contact1 = data;
    }

    /**
     * 002
     *
     * @return java.sql.Timestamp modifyDate
     */
    public java.sql.Timestamp getModifyDate() {
        return this.modifyDate;
    }

    /**
     * 0001
     *
     * @param data Set the modifyDate
     */
    public void setModifyDate(java.sql.Timestamp data) {
        this.modifyDate = data;
    }

    /**
     * 002
     *
     * @return java.lang.String contact2
     */
    public java.lang.String getContact2() {
        return this.contact2;
    }

    /**
     * 0001
     *
     * @param data Set the contact2
     */
    public void setContact2(java.lang.String data) {
        this.contact2 = data;
    }

    /**
     * 002
     *
     * @return java.lang.Long cityId
     */
    public java.lang.Long getCityId() {
        return this.cityId;
    }

    /**
     * 0001
     *
     * @param data Set the cityId
     */
    public void setCityId(java.lang.Long data) {
        this.cityId = data;
    }


    /**
     *
     */
    public Company() {
    }

    /**
     * full constructor
     *
     * @param companyType
     * @param codeName
     * @param companyAddress
     * @param email2
     * @param email1
     * @param taxNo
     * @param contactPhone1
     * @param contactPhone2
     * @param bottomBanner
     * @param verifyStatus
     * @param fax
     * @param createDate
     * @param companyId
     * @param businessNo
     * @param companyKey
     * @param mailingAddress
     * @param phone
     * @param parentId
     * @param name
     * @param creatorId
     * @param modifierId
     * @param taxOffice
     * @param topBanner
     * @param transferType
     * @param contact1
     * @param modifyDate
     * @param contact2
     * @param cityId
     */
    public Company(
            java.lang.Long companyType
            , java.lang.String codeName
            , java.lang.String companyAddress
            , java.lang.String email2
            , java.lang.String email1
            , java.lang.String taxNo
            , java.lang.String contactPhone1
            , java.lang.String contactPhone2
            , java.lang.String bottomBanner
            , java.lang.Long verifyStatus
            , java.lang.String fax
            , java.sql.Timestamp createDate
            , java.lang.Long companyId
            , java.lang.String businessNo
            , java.lang.String companyKey
            , java.lang.String mailingAddress
            , java.lang.String phone
            , java.lang.Long parentId
            , java.lang.String name
            , java.lang.Long creatorId
            , java.lang.Long modifierId
            , java.lang.String taxOffice
            , java.lang.String topBanner
            , java.lang.Long transferType
            , java.lang.String contact1
            , java.sql.Timestamp modifyDate
            , java.lang.String contact2
            , java.lang.Long cityId
    ) {
        this.setCompanyType(companyType);
        this.setCodeName(codeName);
        this.setCompanyAddress(companyAddress);
        this.setEmail2(email2);
        this.setEmail1(email1);
        this.setTaxNo(taxNo);
        this.setContactPhone1(contactPhone1);
        this.setContactPhone2(contactPhone2);
        this.setBottomBanner(bottomBanner);
        this.setVerifyStatus(verifyStatus);
        this.setFax(fax);
        this.setCreateDate(createDate);
        this.setCompanyId(companyId);
        this.setBusinessNo(businessNo);
        this.setCompanyKey(companyKey);
        this.setMailingAddress(mailingAddress);
        this.setPhone(phone);
        this.setParentId(parentId);
        this.setName(name);
        this.setCreatorId(creatorId);
        this.setModifierId(modifierId);
        this.setTaxOffice(taxOffice);
        this.setTopBanner(topBanner);
        this.setTransferType(transferType);
        this.setContact1(contact1);
        this.setModifyDate(modifyDate);
        this.setContact2(contact2);
        this.setCityId(cityId);
    }

    @Override
    public int hashCode() {

        return Objects.hash(companyType, codeName, companyAddress, email2, email1, taxNo, contactPhone1, contactPhone2, bottomBanner, verifyStatus, fax, createDate, companyId, businessNo, companyKey, mailingAddress, phone, parentId, name, creatorId, modifierId, taxOffice, topBanner, transferType, contact1, modifyDate, contact2, cityId);
    }

    @Override
    public String toString() {
        return "Company{" +
                "companyType=" + companyType +
                ", codeName='" + codeName + '\'' +
                ", companyAddress='" + companyAddress + '\'' +
                ", email2='" + email2 + '\'' +
                ", email1='" + email1 + '\'' +
                ", taxNo='" + taxNo + '\'' +
                ", contactPhone1='" + contactPhone1 + '\'' +
                ", contactPhone2='" + contactPhone2 + '\'' +
                ", bottomBanner='" + bottomBanner + '\'' +
                ", verifyStatus=" + verifyStatus +
                ", fax='" + fax + '\'' +
                ", createDate=" + createDate +
                ", companyId=" + companyId +
                ", businessNo='" + businessNo + '\'' +
                ", companyKey='" + companyKey + '\'' +
                ", mailingAddress='" + mailingAddress + '\'' +
                ", phone='" + phone + '\'' +
                ", parentId=" + parentId +
                ", name='" + name + '\'' +
                ", creatorId=" + creatorId +
                ", modifierId=" + modifierId +
                ", taxOffice='" + taxOffice + '\'' +
                ", topBanner='" + topBanner + '\'' +
                ", transferType=" + transferType +
                ", contact1='" + contact1 + '\'' +
                ", modifyDate=" + modifyDate +
                ", contact2='" + contact2 + '\'' +
                ", cityId=" + cityId +
                '}';
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     *
     * @return true is equal, false is not equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Company))
            return false;

        Company key = (Company) obj;
        if (this.companyId != key.companyId)
            return false;

        return true;
    }

}